node {
  name: "tensor_0_odule/model/0/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 32
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 32
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/add_fwd_bf16/1580"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/0/placeholder/0"
  input: "tensor_1_odule/model/0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/0/placeholder/0  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/0/placeholder/1  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/1581"
  op: "rms_norm_ex_fwd_bf16"
  input: "module/model/0/add_fwd_bf16/1580"
  input: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1  |  Sizes = [4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 2]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_9  |  Sizes = [1,32,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 128, 4, 4]  |  data = 0, sizeInBytes = 128  |  "
    }
  }
}
node {
  name: "tensor_9"
  op: "OutputTensor"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/1581"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 32
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/abs_fwd_bf16/1582"
  op: "abs_fwd_bf16"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/1581"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_8  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10_id_12647_module/model/0/gate_proj/aten__abs  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/0/gate_proj/reshape/1583"
  op: "Reshape"
  input: "module/model/0/gate_proj/abs_fwd_bf16/1582"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_10_id_12647_module/model/0/gate_proj/aten__abs  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_tensor_10_id_12647_module/model/0/gate_proj/aten__abs  |  Sizes = [131072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/0/gate_proj/reduce_max_fwd_bf16/1584"
  op: "reduce_max_fwd_bf16"
  input: "module/model/0/gate_proj/reshape/1583"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_tensor_10_id_12647_module/model/0/gate_proj/aten__abs  |  Sizes = [131072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_14  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "module/model/0/gate_proj/reshape/1585"
  op: "Reshape"
  input: "module/model/0/gate_proj/reduce_max_fwd_bf16/1584"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11_id_12649_module/model/0/gate_proj/aten__max  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "module/model/0/gate_proj/reshape/1586"
  op: "Reshape"
  input: "module/model/0/gate_proj/reduce_max_fwd_bf16/1584"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_14  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_15_tensor_14  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_15_tensor_14"
  op: "OutputTensor"
  input: "module/model/0/gate_proj/reshape/1586"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/cast_bf16_to_f32/1587"
  op: "cast_bf16_to_f32"
  input: "module/model/0/gate_proj/reshape/1585"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_id_12649_module/model/0/gate_proj/aten__max  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_17  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_3_odule/model/0/gate_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/max_fwd_f32/1588"
  op: "max_fwd_f32"
  input: "module/model/0/gate_proj/cast_bf16_to_f32/1587"
  input: "tensor_3_odule/model/0/gate_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_3_odule/model/0/gate_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16_id_12651_module/model/0/gate_proj/aten__maximum  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "module/model/0/gate_proj/memcpy/1589"
  op: "Memcpy"
  input: "module/model/0/gate_proj/max_fwd_f32/1588"
  input: "^module/model/0/gate_proj/cast_bf16_to_f32/1587"
  input: "^module/model/0/gate_proj/max_fwd_f32/1588"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_16_id_12651_module/model/0/gate_proj/aten__maximum  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_18"
  op: "OutputTensor"
  input: "module/model/0/gate_proj/memcpy/1589"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/up_proj/cast_bf16_to_f32/1590"
  op: "cast_bf16_to_f32"
  input: "module/model/0/gate_proj/reshape/1585"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_id_12649_module/model/0/gate_proj/aten__max  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_22  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_19_odule/model/0/up_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/up_proj/max_fwd_f32/1591"
  op: "max_fwd_f32"
  input: "module/model/0/up_proj/cast_bf16_to_f32/1590"
  input: "tensor_19_odule/model/0/up_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_22  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_19_odule/model/0/up_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_21_id_12663_module/model/0/up_proj/aten__maximum  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "module/model/0/up_proj/memcpy/1592"
  op: "Memcpy"
  input: "module/model/0/up_proj/max_fwd_f32/1591"
  input: "^module/model/0/up_proj/cast_bf16_to_f32/1590"
  input: "^module/model/0/up_proj/max_fwd_f32/1591"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_21_id_12663_module/model/0/up_proj/aten__maximum  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_23  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
}
node {
  name: "tensor_23"
  op: "OutputTensor"
  input: "module/model/0/up_proj/memcpy/1592"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_26_odule/model/0/up_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 7168
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/up_proj/transpose/1593"
  op: "Transpose"
  input: "tensor_26_odule/model/0/up_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (1,0)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_26_odule/model/0/up_proj/placeholder/0  |  Sizes = [7168,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_27_id_12665_module/model/0/up_proj/aten__transpose  |  Sizes = [4096,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 14336, 2]  |  data = 0, sizeInBytes = 58720256  |  "
    }
  }
}
node {
  name: "module/model/0/up_proj/reshape/1594"
  op: "Reshape"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/1581"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_8  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_28  |  Sizes = [32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/0/up_proj/gemm/1595"
  op: "GEMM"
  input: "module/model/0/up_proj/reshape/1594"
  input: "module/model/0/up_proj/transpose/1593"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_28  |  Sizes = [32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_27_id_12665_module/model/0/up_proj/aten__transpose  |  Sizes = [4096,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 14336, 2]  |  data = 0, sizeInBytes = 58720256  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_29  |  Sizes = [32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/0/up_proj/reshape/1596"
  op: "Reshape"
  input: "module/model/0/up_proj/gemm/1595"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_29  |  Sizes = [32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_30_id_12667_module/model/0/up_proj/aten__matmul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "tensor_31_odule/model/0/gate_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 7168
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/gate_proj/transpose/1597"
  op: "Transpose"
  input: "tensor_31_odule/model/0/gate_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (1,0)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_31_odule/model/0/gate_proj/placeholder/0  |  Sizes = [7168,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_32_id_12653_module/model/0/gate_proj/aten__transpose  |  Sizes = [4096,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 14336, 2]  |  data = 0, sizeInBytes = 58720256  |  "
    }
  }
}
node {
  name: "module/model/0/gate_proj/reshape/1598"
  op: "Reshape"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/1581"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_8  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_33  |  Sizes = [32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/0/gate_proj/gemm/1599"
  op: "GEMM"
  input: "module/model/0/gate_proj/reshape/1598"
  input: "module/model/0/gate_proj/transpose/1597"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_33  |  Sizes = [32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_32_id_12653_module/model/0/gate_proj/aten__transpose  |  Sizes = [4096,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 14336, 2]  |  data = 0, sizeInBytes = 58720256  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_34  |  Sizes = [32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/0/gate_proj/reshape/1600"
  op: "Reshape"
  input: "module/model/0/gate_proj/gemm/1599"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_34  |  Sizes = [32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_35_id_12655_module/model/0/gate_proj/aten__matmul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/0/act_fn/silu_fwd_bf16/1601"
  op: "silu_fwd_bf16"
  input: "module/model/0/gate_proj/reshape/1600"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_35_id_12655_module/model/0/gate_proj/aten__matmul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_36_id_12657_module/model/0/act_fn/aten__silu  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/0/mult_fwd_bf16/1602"
  op: "mult_fwd_bf16"
  input: "module/model/0/act_fn/silu_fwd_bf16/1601"
  input: "module/model/0/up_proj/reshape/1596"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_36_id_12657_module/model/0/act_fn/aten__silu  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_30_id_12667_module/model/0/up_proj/aten__matmul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_37_id_12669_module/model/0/aten__mul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/abs_fwd_bf16/1603"
  op: "abs_fwd_bf16"
  input: "module/model/0/mult_fwd_bf16/1602"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_37_id_12669_module/model/0/aten__mul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/1604"
  op: "Reshape"
  input: "module/model/0/down_proj/abs_fwd_bf16/1603"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [229376]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reduce_max_fwd_bf16/1605"
  op: "reduce_max_fwd_bf16"
  input: "module/model/0/down_proj/reshape/1604"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "25"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [229376]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_42  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/1606"
  op: "Reshape"
  input: "module/model/0/down_proj/reduce_max_fwd_bf16/1605"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "26"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_39_id_12673_module/model/0/down_proj/aten__max  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/1607"
  op: "Reshape"
  input: "module/model/0/down_proj/reduce_max_fwd_bf16/1605"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "27"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_42  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_43_tensor_42  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_43_tensor_42"
  op: "OutputTensor"
  input: "module/model/0/down_proj/reshape/1607"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/0/down_proj/cast_bf16_to_f32/1608"
  op: "cast_bf16_to_f32"
  input: "module/model/0/down_proj/reshape/1606"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "28"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_39_id_12673_module/model/0/down_proj/aten__max  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_24_odule/model/0/down_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/down_proj/max_fwd_f32/1609"
  op: "max_fwd_f32"
  input: "module/model/0/down_proj/cast_bf16_to_f32/1608"
  input: "tensor_24_odule/model/0/down_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "29"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_24_odule/model/0/down_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_44_id_12675_module/model/0/down_proj/aten__maximum  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/memcpy/1610"
  op: "Memcpy"
  input: "module/model/0/down_proj/max_fwd_f32/1609"
  input: "^module/model/0/down_proj/cast_bf16_to_f32/1608"
  input: "^module/model/0/down_proj/max_fwd_f32/1609"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "30"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_44_id_12675_module/model/0/down_proj/aten__maximum  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_46  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
}
node {
  name: "tensor_46"
  op: "OutputTensor"
  input: "module/model/0/down_proj/memcpy/1610"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_47_odule/model/0/down_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 7168
        }
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/down_proj/transpose/1611"
  op: "Transpose"
  input: "tensor_47_odule/model/0/down_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "31"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (1,0)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_47_odule/model/0/down_proj/placeholder/0  |  Sizes = [4096,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 14336, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_48_id_12677_module/model/0/down_proj/aten__transpose  |  Sizes = [7168,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 2]  |  data = 0, sizeInBytes = 58720256  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/1612"
  op: "Reshape"
  input: "module/model/0/mult_fwd_bf16/1602"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "32"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_37_id_12669_module/model/0/aten__mul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49  |  Sizes = [32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/gemm/1613"
  op: "GEMM"
  input: "module/model/0/down_proj/reshape/1612"
  input: "module/model/0/down_proj/transpose/1611"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "33"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49  |  Sizes = [32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_48_id_12677_module/model/0/down_proj/aten__transpose  |  Sizes = [7168,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 2]  |  data = 0, sizeInBytes = 58720256  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_50  |  Sizes = [32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/1614"
  op: "Reshape"
  input: "module/model/0/down_proj/gemm/1613"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "34"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_50  |  Sizes = [32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_51_id_12679_module/model/0/down_proj/aten__matmul  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
}
node {
  name: "tensor_51_id_12679_module/model/0/down_proj/aten__matmul"
  op: "OutputTensor"
  input: "module/model/0/down_proj/reshape/1614"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 32
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
