node {
  name: "tensor_0_odule/model/0/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/add_fwd_bf16/228_complex/add_fwd_bf16_0_bundle_4/op_0"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/0/placeholder/0"
  input: "tensor_1_odule/model/0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/0/placeholder/0  |  Sizes = [1,284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/0/placeholder/1  |  Sizes = [1,284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_4_13331  |  Sizes = [1,284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
}
node {
  name: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/229_complex/rms_norm_ex_fwd_bf16_3/reshape_4_bundle_4/op_1"
  op: "Reshape"
  input: "module/model/0/add_fwd_bf16/228_complex/add_fwd_bf16_0_bundle_4/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_4_13331  |  Sizes = [1,284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-5_13111_slice_0_0_0_0_0__0__bundle_4_13332  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isAliased = tensor_2_slice_0_0_0_0_0__0__bundle_4_13331, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
}
node {
  name: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/229_complex/rms_norm_ex_fwd_bf16_3/rms_norm_fwd_bf16_6_bundle_4/op_2"
  op: "rms_norm_fwd_bf16"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/229_complex/rms_norm_ex_fwd_bf16_3/reshape_4_bundle_4/op_1"
  input: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-5_13111_slice_0_0_0_0_0__0__bundle_4_13332  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isAliased = tensor_2_slice_0_0_0_0_0__0__bundle_4_13331, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1  |  Sizes = [4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 2]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-7_13112_slice_0_0_0_0_0__0__bundle_4_13334  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd288000  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "f32-8_13113  |  Sizes = [284,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1136, 4, 4]  |  data = 0, sizeInBytes = 1136  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  "
    }
  }
}
node {
  name: "f32-8_13113"
  op: "OutputTensor"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/229_complex/rms_norm_ex_fwd_bf16_3/rms_norm_fwd_bf16_6_bundle_4/op_2"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_26_odule/model/0/up_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 7168
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/up_proj/gemm/243_bundle_4/op_3"
  op: "GEMM"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/229_complex/rms_norm_ex_fwd_bf16_3/rms_norm_fwd_bf16_6_bundle_4/op_2"
  input: "tensor_26_odule/model/0/up_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_13112_slice_0_0_0_0_0__0__bundle_4_13334  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd288000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_26_odule/model/0/up_proj/placeholder/0  |  Sizes = [7168,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_29  |  Sizes = [284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  isAliased = tensor-13291, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_31_odule/model/0/gate_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 7168
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/gate_proj/gemm/247_bundle_4/op_4"
  op: "GEMM"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/229_complex/rms_norm_ex_fwd_bf16_3/rms_norm_fwd_bf16_6_bundle_4/op_2"
  input: "tensor_31_odule/model/0/gate_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_13112_slice_0_0_0_0_0__0__bundle_4_13334  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd288000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_31_odule/model/0/gate_proj/placeholder/0  |  Sizes = [7168,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xb0000000000  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_34  |  Sizes = [284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  isAliased = tensor-13290, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_2_bundle_4/memcpy/0"
  op: "DmaMemcpy"
  input: "module/model/0/add_fwd_bf16/228_complex/add_fwd_bf16_0_bundle_4/op_0"
  input: "^module/model/0/add_fwd_bf16/228_complex/add_fwd_bf16_0_bundle_4/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_4_13331  |  Sizes = [1,284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "tensor_2"
  op: "OutputTensor"
  input: "tensor_2_bundle_4/memcpy/0"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "bf16-7_13112_bundle_4/memcpy/0"
  op: "DmaMemcpy"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/229_complex/rms_norm_ex_fwd_bf16_3/rms_norm_fwd_bf16_6_bundle_4/op_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_13112_slice_0_0_0_0_0__0__bundle_4_13334  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd288000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-7_13112  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isAliased = tensor-13289, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "reshape_0_0"
  op: "Reshape"
  input: "bf16-7_13112_bundle_4/memcpy/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_13112  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isAliased = tensor-13289, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-13289  |  Sizes = [1163264]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in DRAM  |  dramOffset = 0x7c4000  |  "
    }
  }
}
node {
  name: "fusedTPCNode_9_0"
  op: "fused_kernel_0x729580A3_11_bf16"
  input: "reshape_0_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-13289  |  Sizes = [1163264]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2]  |  data = 0, sizeInBytes = 2326528  |  location = in DRAM  |  dramOffset = 0x7c4000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_tensor_10_id_12647_module/model/0/gate_proj/aten__abs  |  Sizes = [1163264]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2]  |  data = 0, sizeInBytes = 2326528  |  isAliased = tensor-13289, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor-13293"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/reduce_max_fwd_bf16/232_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  op: "reduce_max_fwd_bf16"
  input: "fusedTPCNode_9_0"
  input: "tensor-13293"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_tensor_10_id_12647_module/model/0/gate_proj/aten__abs  |  Sizes = [1163264]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2]  |  data = 0, sizeInBytes = 2326528  |  isAliased = tensor-13289, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-13293  |  Sizes = [256]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0x5606cda42400, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x10000008200  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0xd0000000480  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_14  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xd0000000500  |  "
    }
  }
}
node {
  name: "tensor_14"
  op: "OutputTensor"
  input: "module/model/0/gate_proj/reduce_max_fwd_bf16/232_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/cast_bf16_to_f32/235"
  op: "cast_bf16_to_f32"
  input: "module/model/0/gate_proj/reduce_max_fwd_bf16/232_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0xd0000000480  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_17  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xd0000000580  |  "
    }
  }
}
node {
  name: "tensor_3_odule/model/0/gate_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/max_fwd_f32/236_complex/max_fwd_f32_0"
  op: "max_fwd_f32"
  input: "module/model/0/gate_proj/cast_bf16_to_f32/235"
  input: "tensor_3_odule/model/0/gate_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xd0000000580  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_3_odule/model/0/gate_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_18"
  op: "OutputTensor"
  input: "module/model/0/gate_proj/max_fwd_f32/236_complex/max_fwd_f32_0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_19_odule/model/0/up_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/up_proj/max_fwd_f32/239_complex/max_fwd_f32_0"
  op: "max_fwd_f32"
  input: "module/model/0/gate_proj/cast_bf16_to_f32/235"
  input: "tensor_19_odule/model/0/up_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xd0000000580  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_19_odule/model/0/up_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_23  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
}
node {
  name: "tensor_23"
  op: "OutputTensor"
  input: "module/model/0/up_proj/max_fwd_f32/239_complex/max_fwd_f32_0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "reshape_3_3"
  op: "Reshape"
  input: "module/model/0/gate_proj/gemm/247_bundle_4/op_4"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_34  |  Sizes = [284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  isAliased = tensor-13290, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-13290  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x3e2000  |  "
    }
  }
}
node {
  name: "reshape_5_5"
  op: "Reshape"
  input: "module/model/0/up_proj/gemm/243_bundle_4/op_3"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_29  |  Sizes = [284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  isAliased = tensor-13291, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-13291  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "fusedTPCNode_9_1_bundle_5/op_0"
  op: "fused_kernel_0xFE87C8C5_12_bf16"
  input: "reshape_3_3"
  input: "reshape_5_5"
  attr {
    key: "Bundle_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-13290  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x3e2000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-13291  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  isAliased = tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor-13292_slice_0_0_0_0_0__0__bundle_5_13346  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  isAliased = tensor_49_slice_0_0_0_0_0__0__bundle_5_13347, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd4c0000  |  "
    }
  }
}
node {
  name: "reshape_9_9_bundle_5/op_1"
  op: "Reshape"
  input: "fusedTPCNode_9_1_bundle_5/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-13292_slice_0_0_0_0_0__0__bundle_5_13346  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  isAliased = tensor_49_slice_0_0_0_0_0__0__bundle_5_13347, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd4c0000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49_slice_0_0_0_0_0__0__bundle_5_13347  |  Sizes = [284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in SRAM  |  sramOffset = 0x1000fffffd4c0000  |  "
    }
  }
}
node {
  name: "tensor_47_odule/model/0/down_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 7168
        }
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/down_proj/gemm/261_bundle_5/op_2"
  op: "GEMM"
  input: "reshape_9_9_bundle_5/op_1"
  input: "tensor_47_odule/model/0/down_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49_slice_0_0_0_0_0__0__bundle_5_13347  |  Sizes = [284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in SRAM  |  sramOffset = 0x1000fffffd4c0000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_47_odule/model/0/down_proj/placeholder/0  |  Sizes = [4096,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 14336, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xc0000000000  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_50  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isAliased = tensor_51_id_12679_module/model/0/down_proj/aten__matmul, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/252"
  op: "Reshape"
  input: "fusedTPCNode_9_1_bundle_5/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  isAliased = tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [2035712]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x9fc000  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reduce_max_fwd_bf16/253_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  op: "reduce_max_fwd_bf16"
  input: "module/model/0/down_proj/reshape/252"
  input: "tensor-13293"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [2035712]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x9fc000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-13293  |  Sizes = [256]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0x5606cda42400, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x10000008200  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0xdde000  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_42  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xdde080  |  "
    }
  }
}
node {
  name: "tensor_42"
  op: "OutputTensor"
  input: "module/model/0/down_proj/reduce_max_fwd_bf16/253_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/0/down_proj/cast_bf16_to_f32/256"
  op: "cast_bf16_to_f32"
  input: "module/model/0/down_proj/reduce_max_fwd_bf16/253_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0xdde000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x7c4000  |  "
    }
  }
}
node {
  name: "tensor_24_odule/model/0/down_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/down_proj/max_fwd_f32/257_complex/max_fwd_f32_0"
  op: "max_fwd_f32"
  input: "module/model/0/down_proj/cast_bf16_to_f32/256"
  input: "tensor_24_odule/model/0/down_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x7c4000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_24_odule/model/0/down_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_46  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
}
node {
  name: "tensor_46"
  op: "OutputTensor"
  input: "module/model/0/down_proj/max_fwd_f32/257_complex/max_fwd_f32_0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/262"
  op: "Reshape"
  input: "module/model/0/down_proj/gemm/261_bundle_5/op_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_50  |  Sizes = [284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isAliased = tensor_51_id_12679_module/model/0/down_proj/aten__matmul, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_51_id_12679_module/model/0/down_proj/aten__matmul  |  Sizes = [1,284,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 2]  |  data = 0, sizeInBytes = 2326528  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
}
node {
  name: "tensor_51_id_12679_module/model/0/down_proj/aten__matmul"
  op: "OutputTensor"
  input: "module/model/0/down_proj/reshape/262"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
