node {
  name: "tensor_7_odule/model/31/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/31/expand_dims/15450"
  op: "ExpandDims"
  input: "tensor_7_odule/model/31/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7_odule/model/31/placeholder/0  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8_id_92698_module/model/31/aten__unsqueeze/1  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7_odule/model/31/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_9_odule/model/31/rotary_emb/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 131072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/31/rotary_emb/slice/15451"
  op: "Slice"
  input: "tensor_9_odule/model/31/rotary_emb/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9_odule/model/31/rotary_emb/placeholder/0  |  Sizes = [131072,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 33554432  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10_id_92816_module/model/31/rotary_emb/aten__slice  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = tensor_9_odule/model/31/rotary_emb/placeholder/0, type = slice, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_11_odule/model/31/rotary_emb/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/31/rotary_emb/cast_f32_to_bf16/15452"
  op: "cast_f32_to_bf16"
  input: "tensor_11_odule/model/31/rotary_emb/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_odule/model/31/rotary_emb/placeholder/1  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0x60000000000  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_emb/mult_fwd_bf16/15453_complex/mult_fwd_bf16_0"
  op: "mult_fwd_bf16"
  input: "module/model/31/rotary_emb/slice/15451"
  input: "module/model/31/rotary_emb/cast_f32_to_bf16/15452"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_10_id_92816_module/model/31/rotary_emb/aten__slice  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = tensor_9_odule/model/31/rotary_emb/placeholder/0, type = slice, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0x60000000000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_92818_module/model/31/rotary_emb/aten__mul  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x60000000080  |  "
    }
  }
}
node {
  name: "tensor_17_odule/model/31/rotary_emb/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 131072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/31/rotary_emb/slice/15457"
  op: "Slice"
  input: "tensor_17_odule/model/31/rotary_emb/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17_odule/model/31/rotary_emb/placeholder/0  |  Sizes = [131072,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 33554432  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18_id_92820_module/model/31/rotary_emb/aten__slice  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = tensor_17_odule/model/31/rotary_emb/placeholder/0, type = slice, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_emb/mult_fwd_bf16/15459_complex/mult_fwd_bf16_0"
  op: "mult_fwd_bf16"
  input: "module/model/31/rotary_emb/slice/15457"
  input: "module/model/31/rotary_emb/cast_f32_to_bf16/15452"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_18_id_92820_module/model/31/rotary_emb/aten__slice  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = tensor_17_odule/model/31/rotary_emb/placeholder/0, type = slice, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0x60000000000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_19_id_92822_module/model/31/rotary_emb/aten__mul  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x130000000000  |  "
    }
  }
}
node {
  name: "tensor_33_odule/model/31/k_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 512
        }
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/31/k_proj/fp8_gemm_bf16/15465_complex/fp8_gemm_bf16_3067/expand_dims_6"
  op: "ExpandDims"
  input: "tensor_33_odule/model/31/k_proj/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_33_odule/model/31/k_proj/placeholder/1  |  Sizes = [4096,512]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 512, 1]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "hf8-7_220046  |  Sizes = [1,4096,512]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 512, 1]  |  data = 0, sizeInBytes = 2097152  |  isAliased = tensor_33_odule/model/31/k_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/gather_nd_mxnet_fwd_bf16_8"
  op: "gather_nd_mxnet_fwd_bf16"
  input: "module/model/31/rotary_emb/mult_fwd_bf16/15459_complex/mult_fwd_bf16_0"
  input: "module/model/31/expand_dims/15450"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_19_id_92822_module/model/31/rotary_emb/aten__mul  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x130000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_8_id_92698_module/model/31/aten__unsqueeze/1  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7_odule/model/31/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-9_220051  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = bf16-13_220053, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/gather_nd_mxnet_fwd_bf16_10"
  op: "gather_nd_mxnet_fwd_bf16"
  input: "module/model/31/rotary_emb/mult_fwd_bf16/15453_complex/mult_fwd_bf16_0"
  input: "module/model/31/expand_dims/15450"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_92818_module/model/31/rotary_emb/aten__mul  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x60000000080  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_8_id_92698_module/model/31/aten__unsqueeze/1  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7_odule/model/31/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-11_220052  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = bf16-15_220054, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/expand_dims_12"
  op: "ExpandDims"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/gather_nd_mxnet_fwd_bf16_8"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-9_220051  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = bf16-13_220053, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-13_220053  |  Sizes = [1,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x140000000000  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/expand_dims_14"
  op: "ExpandDims"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/gather_nd_mxnet_fwd_bf16_10"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-11_220052  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = bf16-15_220054, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-15_220054  |  Sizes = [1,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x140000001000  |  "
    }
  }
}
node {
  name: "tensor_58_odule/model/31/v_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 512
        }
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/31/v_proj/fp8_gemm_bf16/15474_complex/fp8_gemm_hf8_3069/expand_dims_8"
  op: "ExpandDims"
  input: "tensor_58_odule/model/31/v_proj/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_58_odule/model/31/v_proj/placeholder/1  |  Sizes = [4096,512]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 512, 1]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x160000000000  |  userMemorySection(type=Persistent, id=22)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "hf8-9_220059  |  Sizes = [1,4096,512]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 512, 1]  |  data = 0, sizeInBytes = 2097152  |  isAliased = tensor_58_odule/model/31/v_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_73_odule/model/31/fused_scaled_dot_product_attention/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 16
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/31/fused_scaled_dot_product_attention/expand_dims/15485"
  op: "Reshape"
  input: "tensor_73_odule/model/31/fused_scaled_dot_product_attention/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_73_odule/model/31/fused_scaled_dot_product_attention/placeholder/0  |  Sizes = [16,16]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [512, 32, 2]  |  data = 0, sizeInBytes = 512  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x1d0000000000  |  userMemorySection(type=Persistent, id=29)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_79_id_92925_module/model/31/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,1,16,16]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [512, 512, 512, 512, 32, 2]  |  data = 0, sizeInBytes = 512  |  isAliased = tensor_73_odule/model/31/fused_scaled_dot_product_attention/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_95_odule/model/31/q_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2048
        }
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/31/q_proj/fp8_gemm_bf16/15492_complex/fp8_gemm_bf16_3071/expand_dims_6"
  op: "ExpandDims"
  input: "tensor_95_odule/model/31/q_proj/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_95_odule/model/31/q_proj/placeholder/1  |  Sizes = [4096,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 2048, 1]  |  data = 0, sizeInBytes = 8388608  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x210000000000  |  userMemorySection(type=Persistent, id=33)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "hf8-7_220063  |  Sizes = [1,4096,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 2048, 1]  |  data = 0, sizeInBytes = 8388608  |  isAliased = tensor_95_odule/model/31/q_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_0_odule/model/30/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/30/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/30/add_fwd_bf16/15448_complex/add_fwd_bf16_0_bundle_1151/op_0"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/30/placeholder/0"
  input: "tensor_1_odule/model/30/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/30/placeholder/0  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/30/placeholder/1  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_1151_220603  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
}
node {
  name: "module/model/31/input_layernorm/rms_norm_ex_fwd_bf16/15463_complex/rms_norm_ex_fwd_bf16_775/reshape_4_bundle_1151/op_1"
  op: "Reshape"
  input: "module/model/30/add_fwd_bf16/15448_complex/add_fwd_bf16_0_bundle_1151/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_1151_220603  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-5_220040_slice_0_0_0_0_0__0__bundle_1151_220604  |  Sizes = [16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isAliased = tensor_2_slice_0_0_0_0_0__0__bundle_1151_220603, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
}
node {
  name: "tensor_24_odule/model/31/input_layernorm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/31/input_layernorm/rms_norm_ex_fwd_bf16/15463_complex/rms_norm_ex_fwd_bf16_775/rms_norm_fwd_bf16_6_bundle_1151/op_2"
  op: "rms_norm_fwd_bf16"
  input: "module/model/31/input_layernorm/rms_norm_ex_fwd_bf16/15463_complex/rms_norm_ex_fwd_bf16_775/reshape_4_bundle_1151/op_1"
  input: "tensor_24_odule/model/31/input_layernorm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-5_220040_slice_0_0_0_0_0__0__bundle_1151_220604  |  Sizes = [16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isAliased = tensor_2_slice_0_0_0_0_0__0__bundle_1151_220603, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_24_odule/model/31/input_layernorm/placeholder/1  |  Sizes = [4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 2]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xb0000000000  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-7_220041_slice_0_0_0_0_0__0__bundle_1151_220606  |  Sizes = [16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isAliased = tensor-220259_slice_0_0_0_0_0__0__bundle_1151_220608, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd070000  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "f32-8_220042  |  Sizes = [16,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0x60000001080  |  "
    }
  }
}
node {
  name: "f32-8_220042"
  op: "OutputTensor"
  input: "module/model/31/input_layernorm/rms_norm_ex_fwd_bf16/15463_complex/rms_norm_ex_fwd_bf16_775/rms_norm_fwd_bf16_6_bundle_1151/op_2"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "reshape_0_0_bundle_1151/op_3"
  op: "Reshape"
  input: "module/model/31/input_layernorm/rms_norm_ex_fwd_bf16/15463_complex/rms_norm_ex_fwd_bf16_775/rms_norm_fwd_bf16_6_bundle_1151/op_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_220041_slice_0_0_0_0_0__0__bundle_1151_220606  |  Sizes = [16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isAliased = tensor-220259_slice_0_0_0_0_0__0__bundle_1151_220608, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd070000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-220259_slice_0_0_0_0_0__0__bundle_1151_220608  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  location = in SRAM  |  sramOffset = 0x1000fffffd070000  |  "
    }
  }
}
node {
  name: "fusedTPCNode_402_0_bundle_1151/op_4"
  op: "fused_kernel_0x2125B632_48D_hf8"
  input: "reshape_0_0_bundle_1151/op_3"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-220259_slice_0_0_0_0_0__0__bundle_1151_220608  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  location = in SRAM  |  sramOffset = 0x1000fffffd070000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_32_slice_0_0_0_0_0__0__bundle_1151_220609  |  Sizes = [1,16,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 1]  |  data = 0, sizeInBytes = 65536  |  location = in SRAM  |  sramOffset = 0x1000fffffd090000  |  "
    }
  }
}
node {
  name: "module/model/31/k_proj/fp8_gemm_bf16/15465_complex/fp8_gemm_bf16_3067/batch_gemm_8_bundle_1151/op_5_gemm"
  op: "GEMM"
  input: "fusedTPCNode_402_0_bundle_1151/op_4"
  input: "module/model/31/k_proj/fp8_gemm_bf16/15465_complex/fp8_gemm_bf16_3067/expand_dims_6"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "7"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "15"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_32_slice_0_0_0_0_0__0__bundle_1151_220609  |  Sizes = [1,16,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 1]  |  data = 0, sizeInBytes = 65536  |  location = in SRAM  |  sramOffset = 0x1000fffffd090000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "hf8-7_220046  |  Sizes = [1,4096,512]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 512, 1]  |  data = 0, sizeInBytes = 2097152  |  isAliased = tensor_33_odule/model/31/k_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [1,16,512]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 1024, 2]  |  data = 0, sizeInBytes = 16384  |  isAliased = tensor_38_id_92808_module/model/31/aten__view, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/v_proj/fp8_gemm_bf16/15474_complex/fp8_gemm_hf8_3069/batch_gemm_10_bundle_1151/op_6_gemm"
  op: "GEMM"
  input: "fusedTPCNode_402_0_bundle_1151/op_4"
  input: "module/model/31/v_proj/fp8_gemm_bf16/15474_complex/fp8_gemm_hf8_3069/expand_dims_8"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "7"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "15"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "7"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_32_slice_0_0_0_0_0__0__bundle_1151_220609  |  Sizes = [1,16,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 1]  |  data = 0, sizeInBytes = 65536  |  location = in SRAM  |  sramOffset = 0x1000fffffd090000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "hf8-9_220059  |  Sizes = [1,4096,512]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 512, 1]  |  data = 0, sizeInBytes = 2097152  |  isAliased = tensor_58_odule/model/31/v_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_62_c220007  |  Sizes = [1,16,512]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 512, 1]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_63_id_92812_module/model/31/quant_input_0/aten__view_memcpy_220645, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/q_proj/fp8_gemm_bf16/15492_complex/fp8_gemm_bf16_3071/batch_gemm_8_bundle_1151/op_7_gemm"
  op: "GEMM"
  input: "fusedTPCNode_402_0_bundle_1151/op_4"
  input: "module/model/31/q_proj/fp8_gemm_bf16/15492_complex/fp8_gemm_bf16_3071/expand_dims_6"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "7"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "15"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_32_slice_0_0_0_0_0__0__bundle_1151_220609  |  Sizes = [1,16,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 1]  |  data = 0, sizeInBytes = 65536  |  location = in SRAM  |  sramOffset = 0x1000fffffd090000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "hf8-7_220063  |  Sizes = [1,4096,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 2048, 1]  |  data = 0, sizeInBytes = 8388608  |  isAliased = tensor_95_odule/model/31/q_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_99  |  Sizes = [1,16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_100_id_92804_module/model/31/aten__view, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_2_bundle_1151/memcpy/0"
  op: "DmaMemcpy"
  input: "module/model/30/add_fwd_bf16/15448_complex/add_fwd_bf16_0_bundle_1151/op_0"
  input: "^module/model/30/add_fwd_bf16/15448_complex/add_fwd_bf16_0_bundle_1151/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "1151"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_1151_220603  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "tensor_2"
  op: "OutputTensor"
  input: "tensor_2_bundle_1151/memcpy/0"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/31/reshape/15466"
  op: "Reshape"
  input: "module/model/31/k_proj/fp8_gemm_bf16/15465_complex/fp8_gemm_bf16_3067/batch_gemm_8_bundle_1151/op_5_gemm"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [1,16,512]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 1024, 2]  |  data = 0, sizeInBytes = 16384  |  isAliased = tensor_38_id_92808_module/model/31/aten__view, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_38_id_92808_module/model/31/aten__view  |  Sizes = [1,16,4,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 1024, 256, 2]  |  data = 0, sizeInBytes = 16384  |  location = in DRAM  |  dramOffset = 0x1c0000000000  |  "
    }
  }
}
node {
  name: "module/model/31/transpose/15467_transpose_via_logical"
  op: "LogicalTranspose"
  input: "module/model/31/reshape/15466"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_38_id_92808_module/model/31/aten__view  |  Sizes = [1,16,4,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 1024, 256, 2]  |  data = 0, sizeInBytes = 16384  |  location = in DRAM  |  dramOffset = 0x1c0000000000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_39_id_92810_module/model/31/aten__transpose  |  Sizes = [1,4,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 256, 1024, 2]  |  data = 0, sizeInBytes = 16384  |  isAliased = tensor_38_id_92808_module/model/31/aten__view, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/rope_st2_fwd_bf16_16"
  op: "rope_st2_fwd_bf16"
  input: "module/model/31/transpose/15467_transpose_via_logical"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/expand_dims_12"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/expand_dims_14"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "25"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_39_id_92810_module/model/31/aten__transpose  |  Sizes = [1,4,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 256, 1024, 2]  |  data = 0, sizeInBytes = 16384  |  isAliased = tensor_38_id_92808_module/model/31/aten__view, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "bf16-13_220053  |  Sizes = [1,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x140000000000  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "bf16-15_220054  |  Sizes = [1,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x140000001000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1,4,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 4096, 256, 2]  |  data = 0, sizeInBytes = 16384  |  location = in DRAM  |  dramOffset = 0x310000010000  |  "
    }
  }
}
node {
  name: "module/model/31/quant_input_0/reshape/15475"
  op: "Reshape"
  input: "module/model/31/v_proj/fp8_gemm_bf16/15474_complex/fp8_gemm_hf8_3069/batch_gemm_10_bundle_1151/op_6_gemm"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "26"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_62_c220007  |  Sizes = [1,16,512]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 512, 1]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_63_id_92812_module/model/31/quant_input_0/aten__view_memcpy_220645, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_63_id_92812_module/model/31/quant_input_0/aten__view_memcpy_220645  |  Sizes = [1,16,4,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 512, 128, 1]  |  data = 0, sizeInBytes = 8192  |  location = in DRAM  |  dramOffset = 0x130000001000  |  "
    }
  }
}
node {
  name: "tensor_63_id_92812_module/model/31/quant_input_0/aten__view_memcpy_220645_internal"
  op: "DmaMemcpy"
  input: "module/model/31/quant_input_0/reshape/15475"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "27"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_63_id_92812_module/model/31/quant_input_0/aten__view_memcpy_220645  |  Sizes = [1,16,4,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 512, 128, 1]  |  data = 0, sizeInBytes = 8192  |  location = in DRAM  |  dramOffset = 0x130000001000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_63_id_92812_module/model/31/quant_input_0/aten__view  |  Sizes = [1,16,4,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 128, 2048, 1]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_69, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
}
node {
  name: "module/model/31/quant_input_0/transpose/15476_transpose_via_logical"
  op: "LogicalTranspose"
  input: "tensor_63_id_92812_module/model/31/quant_input_0/aten__view_memcpy_220645_internal"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "28"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_63_id_92812_module/model/31/quant_input_0/aten__view  |  Sizes = [1,16,4,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 128, 2048, 1]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_69, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_69  |  Sizes = [1,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x140000000000  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "module/model/31/reshape/15493"
  op: "Reshape"
  input: "module/model/31/q_proj/fp8_gemm_bf16/15492_complex/fp8_gemm_bf16_3071/batch_gemm_8_bundle_1151/op_7_gemm"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "29"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_99  |  Sizes = [1,16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_100_id_92804_module/model/31/aten__view, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_100_id_92804_module/model/31/aten__view  |  Sizes = [1,16,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 256, 2]  |  data = 0, sizeInBytes = 65536  |  location = in DRAM  |  dramOffset = 0x310000000000  |  "
    }
  }
}
node {
  name: "module/model/31/transpose/15494_transpose_via_logical"
  op: "LogicalTranspose"
  input: "module/model/31/reshape/15493"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "30"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_100_id_92804_module/model/31/aten__view  |  Sizes = [1,16,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 256, 2]  |  data = 0, sizeInBytes = 65536  |  location = in DRAM  |  dramOffset = 0x310000000000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_101_id_92806_module/model/31/aten__transpose  |  Sizes = [1,16,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 256, 4096, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_100_id_92804_module/model/31/aten__view, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/gather_nd_mxnet_fwd_bf16_8"
  op: "gather_nd_mxnet_fwd_bf16"
  input: "module/model/31/rotary_emb/mult_fwd_bf16/15459_complex/mult_fwd_bf16_0"
  input: "module/model/31/expand_dims/15450"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "31"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_19_id_92822_module/model/31/rotary_emb/aten__mul  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x130000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_8_id_92698_module/model/31/aten__unsqueeze/1  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7_odule/model/31/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-9_220068  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = bf16-13_220070, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/gather_nd_mxnet_fwd_bf16_10"
  op: "gather_nd_mxnet_fwd_bf16"
  input: "module/model/31/rotary_emb/mult_fwd_bf16/15453_complex/mult_fwd_bf16_0"
  input: "module/model/31/expand_dims/15450"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "32"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_92818_module/model/31/rotary_emb/aten__mul  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x60000000080  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_8_id_92698_module/model/31/aten__unsqueeze/1  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7_odule/model/31/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-11_220069  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = bf16-15_220071, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/expand_dims_12"
  op: "ExpandDims"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/gather_nd_mxnet_fwd_bf16_8"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "33"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-9_220068  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = bf16-13_220070, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-13_220070  |  Sizes = [1,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x130000003000  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/expand_dims_14"
  op: "ExpandDims"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/gather_nd_mxnet_fwd_bf16_10"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "34"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-11_220069  |  Sizes = [16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  isAliased = bf16-15_220071, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-15_220071  |  Sizes = [1,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x310000014000  |  "
    }
  }
}
node {
  name: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/rope_st2_fwd_bf16_16_bundle_1152/op_2"
  op: "rope_st2_fwd_bf16"
  input: "module/model/31/transpose/15494_transpose_via_logical"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/expand_dims_12"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/expand_dims_14"
  attr {
    key: "Bundle_idx"
    value {
      s: "1152"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "35"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_101_id_92806_module/model/31/aten__transpose  |  Sizes = [1,16,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 256, 4096, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_100_id_92804_module/model/31/aten__view, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "bf16-13_220070  |  Sizes = [1,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x130000003000  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "bf16-15_220071  |  Sizes = [1,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 256, 2]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x310000014000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_103_slice_0_0_0_0_0__0__bundle_1152_220627  |  Sizes = [1,16,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 256, 2]  |  data = 0, sizeInBytes = 65536  |  location = in SRAM  |  sramOffset = 0x1000fffffd0a0000  |  "
    }
  }
}
node {
  name: "fusedTPCNode_402_1_bundle_1152/op_0"
  op: "fused_kernel_0xCFE8AF24_48E_bf16"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15468_complex/rotary_pos_embedding_fwd_bf16_382/rope_st2_fwd_bf16_16"
  attr {
    key: "Bundle_idx"
    value {
      s: "1152"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "36"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1,4,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 4096, 256, 2]  |  data = 0, sizeInBytes = 16384  |  location = in DRAM  |  dramOffset = 0x310000010000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_46  |  Sizes = [1,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_49  |  Sizes = [1,4,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 4096, 256, 2]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x130000000000  |  userMemorySection(type=Persistent, id=19)  |  "
    }
  }
  attr {
    key: "outputTensor:2"
    value {
      s: "tensor-220260_slice_0_0_0_0_0__0__bundle_1152_220622  |  Sizes = [1,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_89_id_92921_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1152_220623, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd0b0000  |  "
    }
  }
}
node {
  name: "tensor_46"
  op: "OutputTensor"
  input: "fusedTPCNode_402_1_bundle_1152/op_0"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 16
        }
        dim {
          size: 4
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_49"
  op: "OutputTensor"
  input: "fusedTPCNode_402_1_bundle_1152/op_0"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 16
        }
        dim {
          size: 4
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "reshape_5_5_bundle_1152/op_1"
  op: "Reshape"
  input: "fusedTPCNode_402_1_bundle_1152/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "1152"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "37"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-220260_slice_0_0_0_0_0__0__bundle_1152_220622  |  Sizes = [1,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_89_id_92921_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1152_220623, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd0b0000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_89_id_92921_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1152_220623  |  Sizes = [1,4,1,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  location = in SRAM  |  sramOffset = 0x1000fffffd0b0000  |  "
    }
  }
}
node {
  name: "fusedTPCNode_402_3_bundle_1152/op_3"
  op: "fused_kernel_0xD58077C2_490_hf8"
  input: "module/model/31/rotary_pos_embedding_fwd_bf16/15495_complex/rotary_pos_embedding_fwd_bf16_383/rope_st2_fwd_bf16_16_bundle_1152/op_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "1152"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "38"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_103_slice_0_0_0_0_0__0__bundle_1152_220627  |  Sizes = [1,16,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 256, 2]  |  data = 0, sizeInBytes = 65536  |  location = in SRAM  |  sramOffset = 0x1000fffffd0a0000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-220262_slice_0_0_0_0_0__0__bundle_1152_220628  |  Sizes = [1,16,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  isAliased = tensor_108_id_92919_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1152_220629, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd0b2000  |  "
    }
  }
}
node {
  name: "reshape_11_11_bundle_1152/op_4"
  op: "Reshape"
  input: "fusedTPCNode_402_3_bundle_1152/op_3"
  attr {
    key: "Bundle_idx"
    value {
      s: "1152"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "39"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-220262_slice_0_0_0_0_0__0__bundle_1152_220628  |  Sizes = [1,16,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  isAliased = tensor_108_id_92919_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1152_220629, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd0b2000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_108_id_92919_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1152_220629  |  Sizes = [1,4,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  location = in SRAM  |  sramOffset = 0x1000fffffd0b2000  |  "
    }
  }
}
node {
  name: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/fp8_gemm_hf8_3072/batch_gemm_16_bundle_1152/op_5"
  op: "BatchGemm"
  input: "reshape_11_11_bundle_1152/op_4"
  input: "reshape_5_5_bundle_1152/op_1"
  attr {
    key: "Bundle_idx"
    value {
      s: "1152"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "7"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "7"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_108_id_92919_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1152_220629  |  Sizes = [1,4,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  location = in SRAM  |  sramOffset = 0x1000fffffd0b2000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_89_id_92921_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1152_220623  |  Sizes = [1,4,1,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  location = in SRAM  |  sramOffset = 0x1000fffffd0b0000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-17_220080  |  Sizes = [1,4,4,16,16]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 512, 32, 2]  |  data = 0, sizeInBytes = 8192  |  location = in DRAM  |  dramOffset = 0x310000015000  |  "
    }
  }
}
node {
  name: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/constant_f32_18"
  op: "constant_f32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "41"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "f32-19_220081  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x310000017000  |  "
    }
  }
}
node {
  name: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/constant_f32_20"
  op: "constant_f32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "42"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "f32-21_220082  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x310000017080  |  "
    }
  }
}
node {
  name: "fusedTPCNode_402_2_bundle_1153/op_0"
  op: "fused_kernel_0xD4728D1A_48F_bf16"
  input: "module/model/31/quant_input_0/transpose/15476_transpose_via_logical"
  attr {
    key: "Bundle_idx"
    value {
      s: "1153"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "43"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_69  |  Sizes = [1,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x140000000000  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_72  |  Sizes = [1,4,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 4096, 256, 2]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x1c0000000000  |  userMemorySection(type=Persistent, id=28)  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor-220261_slice_0_0_0_0_0__0__bundle_1153_220633  |  Sizes = [1,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_84_id_92923_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1153_220634, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd0ba000  |  "
    }
  }
}
node {
  name: "tensor_72"
  op: "OutputTensor"
  input: "fusedTPCNode_402_2_bundle_1153/op_0"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 16
        }
        dim {
          size: 4
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "reshape_8_8_bundle_1153/op_1"
  op: "Reshape"
  input: "fusedTPCNode_402_2_bundle_1153/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "1153"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "44"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-220261_slice_0_0_0_0_0__0__bundle_1153_220633  |  Sizes = [1,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_84_id_92923_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1153_220634, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd0ba000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_84_id_92923_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1153_220634  |  Sizes = [1,4,1,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  location = in SRAM  |  sramOffset = 0x1000fffffd0ba000  |  "
    }
  }
}
node {
  name: "tensor_112_odule/model/31/fused_scaled_dot_product_attention/placeholder/7"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/softmax_fwd_hf8_22_bundle_1153/op_2"
  op: "softmax_fwd_hf8"
  input: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/fp8_gemm_hf8_3072/batch_gemm_16_bundle_1152/op_5"
  input: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/constant_f32_18"
  input: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/constant_f32_20"
  input: "tensor_112_odule/model/31/fused_scaled_dot_product_attention/placeholder/7"
  input: "module/model/31/fused_scaled_dot_product_attention/expand_dims/15485"
  attr {
    key: "Bundle_idx"
    value {
      s: "1153"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "45"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-17_220080  |  Sizes = [1,4,4,16,16]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 512, 32, 2]  |  data = 0, sizeInBytes = 8192  |  location = in DRAM  |  dramOffset = 0x310000015000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "f32-19_220081  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x310000017000  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "f32-21_220082  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x310000017080  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_112_odule/model/31/fused_scaled_dot_product_attention/placeholder/7  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x561d6a3af938, sizeInBytes = 4  |  buffer = 16  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x280000000000  |  userMemorySection(type=Persistent, id=40)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:4"
    value {
      s: "tensor_79_id_92925_module/model/31/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,1,16,16]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [512, 512, 512, 512, 32, 2]  |  data = 0, sizeInBytes = 512  |  isAliased = tensor_73_odule/model/31/fused_scaled_dot_product_attention/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "hf8-23_220083_slice_0_0_0_0_0__0__bundle_1153_220640  |  Sizes = [1,4,4,16,16]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 1024, 256, 16, 1]  |  data = 0, sizeInBytes = 4096  |  location = in SRAM  |  sramOffset = 0x1000fffffd0bc000  |  "
    }
  }
}
node {
  name: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/fp8_gemm_hf8_3073/batch_gemm_24_bundle_1153/op_3"
  op: "BatchGemm"
  input: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/softmax_fwd_hf8_22_bundle_1153/op_2"
  input: "reshape_8_8_bundle_1153/op_1"
  attr {
    key: "Bundle_idx"
    value {
      s: "1153"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "46"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "11"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "7"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "7"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "hf8-23_220083_slice_0_0_0_0_0__0__bundle_1153_220640  |  Sizes = [1,4,4,16,16]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 4096, 1024, 256, 16, 1]  |  data = 0, sizeInBytes = 4096  |  location = in SRAM  |  sramOffset = 0x1000fffffd0bc000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_84_id_92923_module/model/31/fused_scaled_dot_product_attention/aten__view_slice_0_0_0_0_0__0__bundle_1153_220634  |  Sizes = [1,4,1,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 2048, 2048, 128, 1]  |  data = 0, sizeInBytes = 8192  |  location = in SRAM  |  sramOffset = 0x1000fffffd0ba000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_120  |  Sizes = [1,4,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  isAliased = tensor_121_id_92944_module/model/31/fused_scaled_dot_product_attention/dequant_output/aten__view, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/fused_scaled_dot_product_attention/dequant_output/reshape/15499"
  op: "Reshape"
  input: "module/model/31/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/15498_complex/sdpa_recomp_fwd_hf8_383/sdpa_recomp_core_fwd_hf8_191/fp8_gemm_hf8_3073/batch_gemm_24_bundle_1153/op_3"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "47"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_120  |  Sizes = [1,4,4,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 8192, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  isAliased = tensor_121_id_92944_module/model/31/fused_scaled_dot_product_attention/dequant_output/aten__view, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_121_id_92944_module/model/31/fused_scaled_dot_product_attention/dequant_output/aten__view  |  Sizes = [1,16,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  location = in DRAM  |  dramOffset = 0x310000000000  |  "
    }
  }
}
node {
  name: "module/model/31/transpose/15501_transpose_via_logical"
  op: "LogicalTranspose"
  input: "module/model/31/fused_scaled_dot_product_attention/dequant_output/reshape/15499"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "48"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_121_id_92944_module/model/31/fused_scaled_dot_product_attention/dequant_output/aten__view  |  Sizes = [1,16,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  location = in DRAM  |  dramOffset = 0x310000000000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_125_id_92949_module/model/31/aten__transpose  |  Sizes = [1,16,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 128, 2048, 1]  |  data = 0, sizeInBytes = 32768  |  isAliased = tensor_121_id_92944_module/model/31/fused_scaled_dot_product_attention/dequant_output/aten__view, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
}
node {
  name: "tensor_125_id_92949_module/model/31/aten__transpose_memcpy_220646_internal"
  op: "DmaMemcpy"
  input: "module/model/31/transpose/15501_transpose_via_logical"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "49"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_125_id_92949_module/model/31/aten__transpose  |  Sizes = [1,16,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 128, 2048, 1]  |  data = 0, sizeInBytes = 32768  |  isAliased = tensor_121_id_92944_module/model/31/fused_scaled_dot_product_attention/dequant_output/aten__view, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_125_id_92949_module/model/31/aten__transpose_memcpy_220646  |  Sizes = [1,16,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "module/model/31/o_proj/quant_input_0/reshape/15503"
  op: "Reshape"
  input: "tensor_125_id_92949_module/model/31/aten__transpose_memcpy_220646_internal"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "50"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_125_id_92949_module/model/31/aten__transpose_memcpy_220646  |  Sizes = [1,16,16,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 2048, 128, 1]  |  data = 0, sizeInBytes = 32768  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_131_c220008  |  Sizes = [1,16,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 2048, 1]  |  data = 0, sizeInBytes = 32768  |  isAliased = tensor_125_id_92949_module/model/31/aten__transpose_memcpy_220646, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_132_odule/model/31/o_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 2048
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/31/o_proj/fp8_gemm_bf16/15505_complex/fp8_gemm_bf16_3075/expand_dims_6"
  op: "ExpandDims"
  input: "tensor_132_odule/model/31/o_proj/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "51"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_132_odule/model/31/o_proj/placeholder/1  |  Sizes = [2048,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 1]  |  data = 0, sizeInBytes = 8388608  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x2d0000000000  |  userMemorySection(type=Persistent, id=45)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "hf8-7_220087  |  Sizes = [1,2048,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 4096, 1]  |  data = 0, sizeInBytes = 8388608  |  isAliased = tensor_132_odule/model/31/o_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/31/o_proj/fp8_gemm_bf16/15505_complex/fp8_gemm_bf16_3075/batch_gemm_8_bundle_1154/op_0_gemm"
  op: "GEMM"
  input: "module/model/31/o_proj/quant_input_0/reshape/15503"
  input: "module/model/31/o_proj/fp8_gemm_bf16/15505_complex/fp8_gemm_bf16_3075/expand_dims_6"
  attr {
    key: "Bundle_idx"
    value {
      s: "1154"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "52"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "7"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "15"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_131_c220008  |  Sizes = [1,16,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 2048, 1]  |  data = 0, sizeInBytes = 32768  |  isAliased = tensor_125_id_92949_module/model/31/aten__transpose_memcpy_220646, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "hf8-7_220087  |  Sizes = [1,2048,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 4096, 1]  |  data = 0, sizeInBytes = 8388608  |  isAliased = tensor_132_odule/model/31/o_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_136  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x310000000000  |  userMemorySection(type=Persistent, id=49)  |  "
    }
  }
}
node {
  name: "tensor_136"
  op: "OutputTensor"
  input: "module/model/31/o_proj/fp8_gemm_bf16/15505_complex/fp8_gemm_bf16_3075/batch_gemm_8_bundle_1154/op_0_gemm"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
