node {
  name: "tensor_1_odule/model/embed_tokens/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/embed_tokens/embedding_pt_fwd_bf16/17057_complex/reshape_0"
  op: "Reshape"
  input: "tensor_1_odule/model/embed_tokens/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_1_odule/model/embed_tokens/placeholder/1  |  Sizes = [1,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 256, 4]  |  data = 0, sizeInBytes = 256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "i32-1_257667  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isAliased = tensor_1_odule/model/embed_tokens/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/range_i32/17058"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_3_id_246648_module/model/aten__arange  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
}
node {
  name: "tensor_4_odule/model/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "fusedTPCNode_507_0"
  op: "fused_kernel_0xA2FDF656_5BB_i32"
  input: "module/model/range_i32/17058"
  input: "tensor_4_odule/model/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_3_id_246648_module/model/aten__arange  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_4_odule/model/placeholder/0  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-257840  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isAliased = tensor_11_id_246673_module/model/aten__view, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "reshape_2_2"
  op: "Reshape"
  input: "fusedTPCNode_507_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-257840  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isAliased = tensor_11_id_246673_module/model/aten__view, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11_id_246673_module/model/aten__view  |  Sizes = [64,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4, 4]  |  data = 0, sizeInBytes = 256  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
}
node {
  name: "module/model/less_fwd_i32/17064_complex/less_fwd_i32_0"
  op: "less_fwd_i32"
  input: "module/model/range_i32/17058"
  input: "reshape_2_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_3_id_246648_module/model/aten__arange  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_11_id_246673_module/model/aten__view  |  Sizes = [64,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4, 4]  |  data = 0, sizeInBytes = 256  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_246675_module/model/aten__lt  |  Sizes = [64,64]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 64, 1]  |  data = 0, sizeInBytes = 4096  |  isAliased = tensor-257841, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "reshape_3_3"
  op: "Reshape"
  input: "module/model/less_fwd_i32/17064_complex/less_fwd_i32_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_246675_module/model/aten__lt  |  Sizes = [64,64]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 64, 1]  |  data = 0, sizeInBytes = 4096  |  isAliased = tensor-257841, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-257841  |  Sizes = [2,2048]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 2048, 1]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "module/model/constant_i32/17066"
  op: "constant_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_15  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x1000  |  "
    }
  }
}
node {
  name: "tensor_0_odule/model/embed_tokens/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 128256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/embed_tokens/embedding_pt_fwd_bf16/17057_complex/gather_bf16_2"
  op: "gather_bf16"
  input: "tensor_0_odule/model/embed_tokens/placeholder/0"
  input: "module/model/embed_tokens/embedding_pt_fwd_bf16/17057_complex/reshape_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/embed_tokens/placeholder/0  |  Sizes = [128256,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2101346304, 16384, 2]  |  data = 0, sizeInBytes = 2101346304  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "i32-1_257667  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isAliased = tensor_1_odule/model/embed_tokens/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-3_257668  |  Sizes = [64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  isAliased = tensor_2_id_246643_module/model/embed_tokens/aten__embedding, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/embed_tokens/embedding_pt_fwd_bf16/17057_complex/reshape_4"
  op: "Reshape"
  input: "module/model/embed_tokens/embedding_pt_fwd_bf16/17057_complex/gather_bf16_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-3_257668  |  Sizes = [64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  isAliased = tensor_2_id_246643_module/model/embed_tokens/aten__embedding, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2_id_246643_module/model/embed_tokens/aten__embedding  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_2_id_246643_module/model/embed_tokens/aten__embedding"
  op: "OutputTensor"
  input: "module/model/embed_tokens/embedding_pt_fwd_bf16/17057_complex/reshape_4"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "fusedTPCNode_507_1"
  op: "fused_kernel_0xCE86D488_5BC_f32"
  input: "module/model/constant_i32/17066"
  input: "reshape_3_3"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_15  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x1000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-257841  |  Sizes = [2,2048]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4096, 2048, 1]  |  data = 0, sizeInBytes = 4096  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-257842  |  Sizes = [2,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 4096, 2]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_18, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "reshape_7_7"
  op: "Reshape"
  input: "fusedTPCNode_507_1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-257842  |  Sizes = [2,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 4096, 2]  |  data = 0, sizeInBytes = 8192  |  isAliased = tensor_18, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18  |  Sizes = [64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
}
node {
  name: "tensor_18"
  op: "OutputTensor"
  input: "reshape_7_7"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 64
        }
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
