node {
  name: "tensor_0_odule/model/31/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/31/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/31/add_fwd_bf16/2088_complex/add_fwd_bf16_0"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/31/placeholder/0"
  input: "tensor_1_odule/model/31/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/31/placeholder/0  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/31/placeholder/1  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "module/model/norm/rms_norm_ex_fwd_bf16/2089_complex/rms_norm_ex_fwd_bf16_47/reshape_4"
  op: "Reshape"
  input: "module/model/31/add_fwd_bf16/2088_complex/add_fwd_bf16_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-5_243387  |  Sizes = [16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isAliased = tensor_2, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_3_odule/model/norm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/norm/rms_norm_ex_fwd_bf16/2089_complex/rms_norm_ex_fwd_bf16_47/rms_norm_fwd_bf16_6"
  op: "rms_norm_fwd_bf16"
  input: "module/model/norm/rms_norm_ex_fwd_bf16/2089_complex/rms_norm_ex_fwd_bf16_47/reshape_4"
  input: "tensor_3_odule/model/norm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-5_243387  |  Sizes = [16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isAliased = tensor_2, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_3_odule/model/norm/placeholder/1  |  Sizes = [4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 2]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-7_243388  |  Sizes = [16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isAliased = tensor_6, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "f32-8_243389  |  Sizes = [16,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xb0000000000  |  "
    }
  }
}
node {
  name: "f32-8_243389"
  op: "OutputTensor"
  input: "module/model/norm/rms_norm_ex_fwd_bf16/2089_complex/rms_norm_ex_fwd_bf16_47/rms_norm_fwd_bf16_6"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/norm/rms_norm_ex_fwd_bf16/2089_complex/rms_norm_ex_fwd_bf16_47/reshape_9"
  op: "Reshape"
  input: "module/model/norm/rms_norm_ex_fwd_bf16/2089_complex/rms_norm_ex_fwd_bf16_47/rms_norm_fwd_bf16_6"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_243388  |  Sizes = [16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isAliased = tensor_6, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
}
node {
  name: "module/lm_head/slice/2092"
  op: "Slice"
  input: "module/model/norm/rms_norm_ex_fwd_bf16/2089_complex/rms_norm_ex_fwd_bf16_47/reshape_9"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1,16,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_21131_module/lm_head/aten__slice/1  |  Sizes = [1,16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_6, type = slice, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
}
node {
  name: "tensor_12_id_21131_module/lm_head/aten__slice/1_memcpy_243587_internal"
  op: "DmaMemcpy"
  input: "module/lm_head/slice/2092"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_21131_module/lm_head/aten__slice/1  |  Sizes = [1,16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_6, type = slice, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_21131_module/lm_head/aten__slice/1_memcpy_243587  |  Sizes = [1,16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 2]  |  data = 0, sizeInBytes = 65536  |  location = in DRAM  |  dramOffset = 0xb0000000080  |  "
    }
  }
}
node {
  name: "reshape_0_0"
  op: "Reshape"
  input: "tensor_12_id_21131_module/lm_head/aten__slice/1_memcpy_243587_internal"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_21131_module/lm_head/aten__slice/1_memcpy_243587  |  Sizes = [1,16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 65536, 4096, 2]  |  data = 0, sizeInBytes = 65536  |  location = in DRAM  |  dramOffset = 0xb0000000080  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-243561  |  Sizes = [32768]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_12_id_21131_module/lm_head/aten__slice/1_memcpy_243587, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "fusedTPCNode_36_0"
  op: "fused_kernel_0xBF26C50F_76_bf16"
  input: "reshape_0_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-243561  |  Sizes = [32768]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_12_id_21131_module/lm_head/aten__slice/1_memcpy_243587, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_15_tensor_13_id_21133_module/lm_head/aten__abs  |  Sizes = [32768]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor-243561, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor-243562"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/lm_head/reduce_max_fwd_bf16/2095_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  op: "reduce_max_fwd_bf16"
  input: "fusedTPCNode_36_0"
  input: "tensor-243562"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_15_tensor_13_id_21133_module/lm_head/aten__abs  |  Sizes = [32768]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor-243561, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-243562  |  Sizes = [256]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0x5606b45d1400, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x10000007380  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0xb0000010080  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_17  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xb0000010100  |  "
    }
  }
}
node {
  name: "tensor_17"
  op: "OutputTensor"
  input: "module/lm_head/reduce_max_fwd_bf16/2095_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/lm_head/cast_bf16_to_f32/2098"
  op: "cast_bf16_to_f32"
  input: "module/lm_head/reduce_max_fwd_bf16/2095_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_16  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0xb0000010080  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_20  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xb0000010180  |  "
    }
  }
}
node {
  name: "tensor_8_odule/lm_head/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/lm_head/max_fwd_f32/2099_complex/max_fwd_f32_0"
  op: "max_fwd_f32"
  input: "module/lm_head/cast_bf16_to_f32/2098"
  input: "tensor_8_odule/lm_head/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_20  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xb0000010180  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_8_odule/lm_head/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_21  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
}
node {
  name: "tensor_21"
  op: "OutputTensor"
  input: "module/lm_head/max_fwd_f32/2099_complex/max_fwd_f32_0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/lm_head/reshape/2105"
  op: "Reshape"
  input: "module/lm_head/slice/2092"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_21131_module/lm_head/aten__slice/1  |  Sizes = [1,16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 2]  |  data = 0, sizeInBytes = 65536  |  isAliased = tensor_6, type = slice, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 126976  |  isAliased = tensor_12_id_21131_module/lm_head/aten__slice/1, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
}
node {
  name: "tensor_22_odule/lm_head/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2048
        }
        dim {
          size: 128256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/lm_head/gemm/2106_bundle_65/op_0"
  op: "GEMM"
  input: "module/lm_head/reshape/2105"
  input: "tensor_22_odule/lm_head/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "65"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [16,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 2]  |  data = 0, sizeInBytes = 126976  |  isAliased = tensor_12_id_21131_module/lm_head/aten__slice/1, type = alias, offset: 0  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_22_odule/lm_head/placeholder/0  |  Sizes = [128256,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [525336576, 4096, 2]  |  data = 0, sizeInBytes = 525336576  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_28  |  Sizes = [16,128256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4104192, 256512, 2]  |  data = 0, sizeInBytes = 4104192  |  isAliased = tensor_29_id_21141_module/lm_head/aten__matmul, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/lm_head/reshape/2107"
  op: "Reshape"
  input: "module/lm_head/gemm/2106_bundle_65/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_28  |  Sizes = [16,128256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4104192, 256512, 2]  |  data = 0, sizeInBytes = 4104192  |  isAliased = tensor_29_id_21141_module/lm_head/aten__matmul, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_29_id_21141_module/lm_head/aten__matmul  |  Sizes = [1,16,128256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4104192, 4104192, 256512, 2]  |  data = 0, sizeInBytes = 4104192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xb0000000000  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
}
node {
  name: "tensor_29_id_21141_module/lm_head/aten__matmul"
  op: "OutputTensor"
  input: "module/lm_head/reshape/2107"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128256
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
