node {
  name: "tensor_0_odule/model/0/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "tensor_0_odule/model/0/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/0/placeholder/0  |  Sizes = [1,189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_36537  |  Sizes = [1,6048,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 256, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_0_odule/model/0/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_1_odule/model/0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_reshape_TPC_in1"
  op: "StaticReshape"
  input: "tensor_1_odule/model/0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_1_odule/model/0/placeholder/1  |  Sizes = [1,189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_36538  |  Sizes = [1,6048,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 256, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_1_odule/model/0/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_optimized"
  op: "add_fwd_bf16"
  input: "module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_reshape_TPC_out1"
  input: "module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_reshape_TPC_in1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_36537  |  Sizes = [1,6048,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 256, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_0_odule/model/0/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "_reshaped_36538  |  Sizes = [1,6048,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 256, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_1_odule/model/0/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_36541  |  Sizes = [1,6048,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 256, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_2, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_reshape_TPC_out0"
  op: "StaticReshape"
  input: "module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_optimized"
  input: "^module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_reshape_TPC_out1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_36541  |  Sizes = [1,6048,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 256, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_2, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/567_complex/rms_norm_ex_fwd_bf16_11/reshape_4"
  op: "Reshape"
  input: "module/model/0/add_fwd_bf16/566_complex/add_fwd_bf16_0_reshape_TPC_out0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-5_36354  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_2, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/567_complex/rms_norm_ex_fwd_bf16_11/rms_norm_fwd_bf16_6_bundle_15/op_0"
  op: "rms_norm_fwd_bf16"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/567_complex/rms_norm_ex_fwd_bf16_11/reshape_4"
  input: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-5_36354  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_2, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_5_odule/model/0/post_attention_layernorm/placeholder/1  |  Sizes = [4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 2]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-7_36355_slice_0_0_0_0_0__0__bundle_15_36584  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "f32-8_36356  |  Sizes = [189,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [756, 4, 4]  |  data = 0, sizeInBytes = 756  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  "
    }
  }
}
node {
  name: "f32-8_36356"
  op: "OutputTensor"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/567_complex/rms_norm_ex_fwd_bf16_11/rms_norm_fwd_bf16_6_bundle_15/op_0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_26_odule/model/0/up_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 7168
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/up_proj/gemm/581_bundle_15/op_1"
  op: "GEMM"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/567_complex/rms_norm_ex_fwd_bf16_11/rms_norm_fwd_bf16_6_bundle_15/op_0"
  input: "tensor_26_odule/model/0/up_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_36355_slice_0_0_0_0_0__0__bundle_15_36584  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_26_odule/model/0/up_proj/placeholder/0  |  Sizes = [7168,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_29  |  Sizes = [189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  isAliased = tensor-36534, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_31_odule/model/0/gate_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 7168
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/gate_proj/gemm/585_bundle_15/op_2"
  op: "GEMM"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/567_complex/rms_norm_ex_fwd_bf16_11/rms_norm_fwd_bf16_6_bundle_15/op_0"
  input: "tensor_31_odule/model/0/gate_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_36355_slice_0_0_0_0_0__0__bundle_15_36584  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_31_odule/model/0/gate_proj/placeholder/0  |  Sizes = [7168,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xb0000000000  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_34  |  Sizes = [189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  isAliased = tensor-36533, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "bf16-7_36355_bundle_15/memcpy/0"
  op: "DmaMemcpy"
  input: "module/model/0/post_attention_layernorm/rms_norm_ex_fwd_bf16/567_complex/rms_norm_ex_fwd_bf16_11/rms_norm_fwd_bf16_6_bundle_15/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_36355_slice_0_0_0_0_0__0__bundle_15_36584  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-7_36355  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor-36532, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "reshape_0_0"
  op: "Reshape"
  input: "bf16-7_36355_bundle_15/memcpy/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_36355  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor-36532, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-36532  |  Sizes = [774144]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 2]  |  data = 0, sizeInBytes = 1548288  |  location = in DRAM  |  dramOffset = 0x52b000  |  "
    }
  }
}
node {
  name: "fusedTPCNode_14_0"
  op: "fused_kernel_0xC0E26B80_24_bf16"
  input: "reshape_0_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-36532  |  Sizes = [774144]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 2]  |  data = 0, sizeInBytes = 1548288  |  location = in DRAM  |  dramOffset = 0x52b000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_tensor_10_id_12647_module/model/0/gate_proj/aten__abs  |  Sizes = [774144]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor-36532, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor-36536"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/reduce_max_fwd_bf16/570_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  op: "reduce_max_fwd_bf16"
  input: "fusedTPCNode_14_0"
  input: "tensor-36536"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_tensor_10_id_12647_module/model/0/gate_proj/aten__abs  |  Sizes = [774144]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor-36532, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-36536  |  Sizes = [256]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0x5606cf778800, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x10000008300  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0xd0000000300  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_14  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xd0000000380  |  "
    }
  }
}
node {
  name: "tensor_14"
  op: "OutputTensor"
  input: "module/model/0/gate_proj/reduce_max_fwd_bf16/570_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/cast_bf16_to_f32/573"
  op: "cast_bf16_to_f32"
  input: "module/model/0/gate_proj/reduce_max_fwd_bf16/570_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0xd0000000300  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_17  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xd0000000400  |  "
    }
  }
}
node {
  name: "tensor_3_odule/model/0/gate_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/gate_proj/max_fwd_f32/574_complex/max_fwd_f32_0"
  op: "max_fwd_f32"
  input: "module/model/0/gate_proj/cast_bf16_to_f32/573"
  input: "tensor_3_odule/model/0/gate_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xd0000000400  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_3_odule/model/0/gate_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_18"
  op: "OutputTensor"
  input: "module/model/0/gate_proj/max_fwd_f32/574_complex/max_fwd_f32_0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_19_odule/model/0/up_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/up_proj/max_fwd_f32/577_complex/max_fwd_f32_0"
  op: "max_fwd_f32"
  input: "module/model/0/gate_proj/cast_bf16_to_f32/573"
  input: "tensor_19_odule/model/0/up_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0xd0000000400  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_19_odule/model/0/up_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_23  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
}
node {
  name: "tensor_23"
  op: "OutputTensor"
  input: "module/model/0/up_proj/max_fwd_f32/577_complex/max_fwd_f32_0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "reshape_3_3"
  op: "Reshape"
  input: "module/model/0/gate_proj/gemm/585_bundle_15/op_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_34  |  Sizes = [189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  isAliased = tensor-36533, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-36533  |  Sizes = [1,189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  location = in DRAM  |  dramOffset = 0x295800  |  "
    }
  }
}
node {
  name: "reshape_5_5"
  op: "Reshape"
  input: "module/model/0/up_proj/gemm/581_bundle_15/op_1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_29  |  Sizes = [189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  isAliased = tensor-36534, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-36534  |  Sizes = [1,189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "fusedTPCNode_14_1_bundle_16/op_0"
  op: "fused_kernel_0xE1A48E3F_25_bf16"
  input: "reshape_3_3"
  input: "reshape_5_5"
  attr {
    key: "Bundle_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-36533  |  Sizes = [1,189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  location = in DRAM  |  dramOffset = 0x295800  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-36534  |  Sizes = [1,189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [1,189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  isAliased = tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor-36535_slice_0_0_0_0_0__0__bundle_16_36593  |  Sizes = [1,189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  isAliased = tensor_49_slice_0_0_0_0_0__0__bundle_16_36594, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd1ca000  |  "
    }
  }
}
node {
  name: "reshape_9_9_bundle_16/op_1"
  op: "Reshape"
  input: "fusedTPCNode_14_1_bundle_16/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-36535_slice_0_0_0_0_0__0__bundle_16_36593  |  Sizes = [1,189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  isAliased = tensor_49_slice_0_0_0_0_0__0__bundle_16_36594, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd1ca000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49_slice_0_0_0_0_0__0__bundle_16_36594  |  Sizes = [189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  location = in SRAM  |  sramOffset = 0x1000fffffd1ca000  |  "
    }
  }
}
node {
  name: "tensor_47_odule/model/0/down_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 7168
        }
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/0/down_proj/gemm/599_bundle_16/op_2"
  op: "GEMM"
  input: "reshape_9_9_bundle_16/op_1"
  input: "tensor_47_odule/model/0/down_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49_slice_0_0_0_0_0__0__bundle_16_36594  |  Sizes = [189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  location = in SRAM  |  sramOffset = 0x1000fffffd1ca000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_47_odule/model/0/down_proj/placeholder/0  |  Sizes = [4096,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 14336, 2]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xc0000000000  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_50  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_51_id_12679_module/model/0/down_proj/aten__matmul, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/590"
  op: "Reshape"
  input: "fusedTPCNode_14_1_bundle_16/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [1,189,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2709504, 14336, 2]  |  data = 0, sizeInBytes = 2709504  |  isAliased = tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [1354752]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2]  |  data = 0, sizeInBytes = 2709504  |  location = in DRAM  |  dramOffset = 0x6a5000  |  "
    }
  }
}
node {
  name: "module/model/0/down_proj/reduce_max_fwd_bf16/591_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  op: "reduce_max_fwd_bf16"
  input: "module/model/0/down_proj/reshape/590"
  input: "tensor-36536"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_40_tensor_38_id_12671_module/model/0/down_proj/aten__abs  |  Sizes = [1354752]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2709504, 2]  |  data = 0, sizeInBytes = 2709504  |  location = in DRAM  |  dramOffset = 0x6a5000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-36536  |  Sizes = [256]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0x5606cf778800, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x10000008300  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0x93a800  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_42  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x93a880  |  "
    }
  }
}
node {
  name: "tensor_42"
  op: "OutputTensor"
  input: "module/model/0/down_proj/reduce_max_fwd_bf16/591_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/0/down_proj/cast_bf16_to_f32/594"
  op: "cast_bf16_to_f32"
  input: "module/model/0/down_proj/reduce_max_fwd_bf16/591_complex/reduce_max_fwd_bf16_0_complex/reduce_max_fwd_bf16_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  location = in DRAM  |  dramOffset = 0x93a800  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x52b000  |  "
    }
  }
}
node {
  name: "tensor_24_odule/model/0/down_proj/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/down_proj/max_fwd_f32/595_complex/max_fwd_f32_0"
  op: "max_fwd_f32"
  input: "module/model/0/down_proj/cast_bf16_to_f32/594"
  input: "tensor_24_odule/model/0/down_proj/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x52b000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_24_odule/model/0/down_proj/placeholder/0  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_46  |  Sizes = [1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
}
node {
  name: "tensor_46"
  op: "OutputTensor"
  input: "module/model/0/down_proj/max_fwd_f32/595_complex/max_fwd_f32_0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/0/down_proj/reshape/600"
  op: "Reshape"
  input: "module/model/0/down_proj/gemm/599_bundle_16/op_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_50  |  Sizes = [189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isAliased = tensor_51_id_12679_module/model/0/down_proj/aten__matmul, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_51_id_12679_module/model/0/down_proj/aten__matmul  |  Sizes = [1,189,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 2]  |  data = 0, sizeInBytes = 1548288  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
}
node {
  name: "tensor_51_id_12679_module/model/0/down_proj/aten__matmul"
  op: "OutputTensor"
  input: "module/model/0/down_proj/reshape/600"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
