node {
  name: "tensor_0_odule/model/79/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 128
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/79/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 128
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/79/add_fwd_bf16/17049"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/79/placeholder/0"
  input: "tensor_1_odule/model/79/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/79/placeholder/0  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/79/placeholder/1  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "tensor_3_odule/model/norm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/norm/rms_norm_ex_fwd_bf16/17050"
  op: "rms_norm_ex_fwd_bf16"
  input: "module/model/79/add_fwd_bf16/17049"
  input: "tensor_3_odule/model/norm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_3_odule/model/norm/placeholder/1  |  Sizes = [8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 2]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_7  |  Sizes = [1,128,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [512, 512, 4, 4]  |  data = 0, sizeInBytes = 512  |  "
    }
  }
}
node {
  name: "tensor_7"
  op: "OutputTensor"
  input: "module/model/norm/rms_norm_ex_fwd_bf16/17050"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 128
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/lm_head/quant_input_0/slice/17051"
  op: "Slice"
  input: "module/model/norm/rms_norm_ex_fwd_bf16/17050"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8_id_201767_module/lm_head/quant_input_0/aten__slice  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  "
    }
  }
}
node {
  name: "module/lm_head/quant_input_0/slice/17052"
  op: "Slice"
  input: "module/lm_head/quant_input_0/slice/17051"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_8_id_201767_module/lm_head/quant_input_0/aten__slice  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_9_id_201769_module/lm_head/quant_input_0/aten__slice  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  "
    }
  }
}
node {
  name: "module/lm_head/quant_input_0/slice/17053"
  op: "Slice"
  input: "module/lm_head/quant_input_0/slice/17052"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9_id_201769_module/lm_head/quant_input_0/aten__slice  |  Sizes = [1,128,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 2097152, 16384, 2]  |  data = 0, sizeInBytes = 2097152  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10_id_201771_module/lm_head/quant_input_0/aten__slice  |  Sizes = [1,128,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [524288, 524288, 4096, 2]  |  data = 0, sizeInBytes = 524288  |  "
    }
  }
}
node {
  name: "tensor_11_odule/lm_head/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/lm_head/quant_input_0/convert_to_fp8_bf16/17054"
  op: "convert_to_fp8_bf16"
  input: "module/lm_head/quant_input_0/slice/17053"
  input: "tensor_11_odule/lm_head/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_10_id_201771_module/lm_head/quant_input_0/aten__slice  |  Sizes = [1,128,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [524288, 524288, 4096, 2]  |  data = 0, sizeInBytes = 524288  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_11_odule/lm_head/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd8aba5b8, sizeInBytes = 2  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_14  |  Sizes = [1,128,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 2048, 1]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
}
node {
  name: "tensor_15_odule/lm_head/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128256
        }
        dim {
          size: 2048
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_16_odule/lm_head/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_17_odule/lm_head/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/lm_head/fp8_gemm_bf16/17055"
  op: "fp8_gemm_bf16"
  input: "module/lm_head/quant_input_0/convert_to_fp8_bf16/17054"
  input: "tensor_15_odule/lm_head/placeholder/1"
  input: "tensor_16_odule/lm_head/placeholder/2"
  input: "tensor_17_odule/lm_head/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_14  |  Sizes = [1,128,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 2048, 1]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_15_odule/lm_head/placeholder/1  |  Sizes = [2048,128256]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [262668288, 128256, 1]  |  data = 0, sizeInBytes = 262668288  |  isPersistent  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_16_odule/lm_head/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd8abac68, sizeInBytes = 2  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=13)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_17_odule/lm_head/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd8abb570, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=14)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_19  |  Sizes = [1,128,128256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32833536, 32833536, 256512, 2]  |  data = 0, sizeInBytes = 32833536  |  isPersistent  |  userMemorySection(type=Persistent, id=16)  |  "
    }
  }
}
node {
  name: "tensor_19"
  op: "OutputTensor"
  input: "module/lm_head/fp8_gemm_bf16/17055"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128256
        }
        dim {
          size: 128
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
