node {
  name: "tensor_7_odule/model/26/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/26/expand_dims/13046"
  op: "ExpandDims"
  input: "tensor_7_odule/model/26/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7_odule/model/26/placeholder/0  |  Sizes = [189]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [756, 4]  |  data = 0, sizeInBytes = 756  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8_id_126719_module/model/26/aten__unsqueeze/1  |  Sizes = [1,189]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [756, 756, 4]  |  data = 0, sizeInBytes = 756  |  "
    }
  }
}
node {
  name: "tensor_73_odule/model/26/fused_scaled_dot_product_attention/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 189
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/expand_dims/13076"
  op: "ExpandDims"
  input: "tensor_73_odule/model/26/fused_scaled_dot_product_attention/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_73_odule/model/26/fused_scaled_dot_product_attention/placeholder/0  |  Sizes = [189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  isPersistent  |  userMemorySection(type=Persistent, id=29)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_74_id_126720_module/model/26/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/expand_dims/13077"
  op: "ExpandDims"
  input: "module/model/26/fused_scaled_dot_product_attention/expand_dims/13076"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_74_id_126720_module/model/26/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_75_id_126721_module/model/26/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
}
node {
  name: "module/model/26/expand_dims/13086"
  op: "ExpandDims"
  input: "tensor_7_odule/model/26/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7_odule/model/26/placeholder/0  |  Sizes = [189]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [756, 4]  |  data = 0, sizeInBytes = 756  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_90_id_126719_module/model/26/aten__unsqueeze  |  Sizes = [1,189]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [756, 756, 4]  |  data = 0, sizeInBytes = 756  |  "
    }
  }
}
node {
  name: "tensor_0_odule/model/25/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/25/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/25/add_fwd_bf16/13044"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/25/placeholder/0"
  input: "tensor_1_odule/model/25/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/25/placeholder/0  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/25/placeholder/1  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "tensor_24_odule/model/26/input_layernorm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/input_layernorm/rms_norm_ex_fwd_bf16/13059"
  op: "rms_norm_ex_fwd_bf16"
  input: "module/model/25/add_fwd_bf16/13044"
  input: "tensor_24_odule/model/26/input_layernorm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_24_odule/model/26/input_layernorm/placeholder/1  |  Sizes = [8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 2]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_28  |  Sizes = [1,189,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [756, 756, 4, 4]  |  data = 0, sizeInBytes = 756  |  "
    }
  }
}
node {
  name: "tensor_28"
  op: "OutputTensor"
  input: "module/model/26/input_layernorm/rms_norm_ex_fwd_bf16/13059"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_29_odule/model/26/k_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/k_proj/quant_input_0/convert_to_fp8_bf16/13060"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/input_layernorm/rms_norm_ex_fwd_bf16/13059"
  input: "tensor_29_odule/model/26/k_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_29_odule/model/26/k_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db6bf5fea8, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=12)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_32  |  Sizes = [1,189,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 1]  |  data = 0, sizeInBytes = 1548288  |  "
    }
  }
}
node {
  name: "tensor_9_odule/model/26/rotary_emb/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 131072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/rotary_emb/slice/13047"
  op: "Slice"
  input: "tensor_9_odule/model/26/rotary_emb/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9_odule/model/26/rotary_emb/placeholder/0  |  Sizes = [131072,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 33554432  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10_id_126837_module/model/26/rotary_emb/aten__slice  |  Sizes = [189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "tensor_11_odule/model/26/rotary_emb/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/26/rotary_emb/cast_f32_to_bf16/13048"
  op: "cast_f32_to_bf16"
  input: "tensor_11_odule/model/26/rotary_emb/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_odule/model/26/rotary_emb/placeholder/1  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "tensor_17_odule/model/26/rotary_emb/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 131072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/rotary_emb/slice/13053"
  op: "Slice"
  input: "tensor_17_odule/model/26/rotary_emb/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17_odule/model/26/rotary_emb/placeholder/0  |  Sizes = [131072,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 33554432  |  isPersistent  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18_id_126841_module/model/26/rotary_emb/aten__slice  |  Sizes = [189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/rotary_emb/cast_f32_to_bf16/13054"
  op: "cast_f32_to_bf16"
  input: "tensor_11_odule/model/26/rotary_emb/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_odule/model/26/rotary_emb/placeholder/1  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_20  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "tensor_33_odule/model/26/k_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_34_odule/model/26/k_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_35_odule/model/26/k_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/k_proj/fp8_gemm_bf16/13061"
  op: "fp8_gemm_bf16"
  input: "module/model/26/k_proj/quant_input_0/convert_to_fp8_bf16/13060"
  input: "tensor_33_odule/model/26/k_proj/placeholder/1"
  input: "tensor_34_odule/model/26/k_proj/placeholder/2"
  input: "tensor_35_odule/model/26/k_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_32  |  Sizes = [1,189,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 1]  |  data = 0, sizeInBytes = 1548288  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_33_odule/model/26/k_proj/placeholder/1  |  Sizes = [8192,256]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 256, 1]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_34_odule/model/26/k_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db6743a6d0, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=14)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_35_odule/model/26/k_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db6bf5ece8, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=15)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [1,189,256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 512, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
}
node {
  name: "module/model/26/reshape/13062"
  op: "Reshape"
  input: "module/model/26/k_proj/fp8_gemm_bf16/13061"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [1,189,256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 512, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_38_id_126829_module/model/26/aten__view  |  Sizes = [1,189,2,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 512, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
}
node {
  name: "tensor_54_odule/model/26/v_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/v_proj/quant_input_0/convert_to_fp8_bf16/13069"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/input_layernorm/rms_norm_ex_fwd_bf16/13059"
  input: "tensor_54_odule/model/26/v_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_54_odule/model/26/v_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db6b34fc90, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=21)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_57  |  Sizes = [1,189,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 1]  |  data = 0, sizeInBytes = 1548288  |  "
    }
  }
}
node {
  name: "module/model/26/rotary_emb/mult_fwd_bf16/13049"
  op: "mult_fwd_bf16"
  input: "module/model/26/rotary_emb/slice/13047"
  input: "module/model/26/rotary_emb/cast_f32_to_bf16/13048"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_10_id_126837_module/model/26/rotary_emb/aten__slice  |  Sizes = [189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_126839_module/model/26/rotary_emb/aten__mul  |  Sizes = [189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/expand_dims/13050"
  op: "ExpandDims"
  input: "module/model/26/rotary_emb/mult_fwd_bf16/13049"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_126839_module/model/26/rotary_emb/aten__mul  |  Sizes = [189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_14_id_126861_module/model/26/aten__unsqueeze  |  Sizes = [1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/expand_dims/13051"
  op: "ExpandDims"
  input: "module/model/26/expand_dims/13050"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_14_id_126861_module/model/26/aten__unsqueeze  |  Sizes = [1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_15_id_126863_module/model/26/aten__unsqueeze  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/identity/13052"
  op: "Identity"
  input: "module/model/26/expand_dims/13051"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_15_id_126863_module/model/26/aten__unsqueeze  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16_id_126865_module/model/26/aten__clone  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/rotary_emb/mult_fwd_bf16/13055"
  op: "mult_fwd_bf16"
  input: "module/model/26/rotary_emb/slice/13053"
  input: "module/model/26/rotary_emb/cast_f32_to_bf16/13054"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_18_id_126841_module/model/26/rotary_emb/aten__slice  |  Sizes = [189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_20  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_19_id_126843_module/model/26/rotary_emb/aten__mul  |  Sizes = [189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/expand_dims/13056"
  op: "ExpandDims"
  input: "module/model/26/rotary_emb/mult_fwd_bf16/13055"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_19_id_126843_module/model/26/rotary_emb/aten__mul  |  Sizes = [189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_21_id_126867_module/model/26/aten__unsqueeze  |  Sizes = [1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/expand_dims/13057"
  op: "ExpandDims"
  input: "module/model/26/expand_dims/13056"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_21_id_126867_module/model/26/aten__unsqueeze  |  Sizes = [1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_22_id_126869_module/model/26/aten__unsqueeze  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/identity/13058"
  op: "Identity"
  input: "module/model/26/expand_dims/13057"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_22_id_126869_module/model/26/aten__unsqueeze  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_23_id_126871_module/model/26/aten__clone  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/transpose/13063"
  op: "Transpose"
  input: "module/model/26/reshape/13062"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_38_id_126829_module/model/26/aten__view  |  Sizes = [1,189,2,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 512, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_39_id_126831_module/model/26/aten__transpose  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
}
node {
  name: "tensor_58_odule/model/26/v_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_59_odule/model/26/v_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_60_odule/model/26/v_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/v_proj/fp8_gemm_bf16/13070"
  op: "fp8_gemm_bf16"
  input: "module/model/26/v_proj/quant_input_0/convert_to_fp8_bf16/13069"
  input: "tensor_58_odule/model/26/v_proj/placeholder/1"
  input: "tensor_59_odule/model/26/v_proj/placeholder/2"
  input: "tensor_60_odule/model/26/v_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_57  |  Sizes = [1,189,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 1]  |  data = 0, sizeInBytes = 1548288  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_58_odule/model/26/v_proj/placeholder/1  |  Sizes = [8192,256]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 256, 1]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=22)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_59_odule/model/26/v_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db60389d08, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=23)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_60_odule/model/26/v_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db60388d80, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=24)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_62  |  Sizes = [1,189,256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 512, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
}
node {
  name: "module/model/26/quant_input_0/reshape/13071"
  op: "Reshape"
  input: "module/model/26/v_proj/fp8_gemm_bf16/13070"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_62  |  Sizes = [1,189,256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 512, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_63_id_126833_module/model/26/quant_input_0/aten__view  |  Sizes = [1,189,2,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 512, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
}
node {
  name: "tensor_91_odule/model/26/q_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/q_proj/quant_input_0/convert_to_fp8_bf16/13087"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/input_layernorm/rms_norm_ex_fwd_bf16/13059"
  input: "tensor_91_odule/model/26/q_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "25"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_91_odule/model/26/q_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db61bdfa70, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=32)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_94  |  Sizes = [1,189,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 1]  |  data = 0, sizeInBytes = 1548288  |  "
    }
  }
}
node {
  name: "module/model/26/rotary_pos_embedding_fwd_bf16/13064"
  op: "rotary_pos_embedding_fwd_bf16"
  input: "module/model/26/transpose/13063"
  input: "module/model/26/identity/13058"
  input: "module/model/26/identity/13052"
  input: "module/model/26/expand_dims/13046"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "26"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_39_id_126831_module/model/26/aten__transpose  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_23_id_126871_module/model/26/aten__clone  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_16_id_126865_module/model/26/aten__clone  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_8_id_126719_module/model/26/aten__unsqueeze/1  |  Sizes = [1,189]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [756, 756, 4]  |  data = 0, sizeInBytes = 756  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
}
node {
  name: "module/model/26/quant_input_0/transpose/13072"
  op: "Transpose"
  input: "module/model/26/quant_input_0/reshape/13071"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "27"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_63_id_126833_module/model/26/quant_input_0/aten__view  |  Sizes = [1,189,2,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 512, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_64_id_126835_module/model/26/quant_input_0/aten__transpose  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
}
node {
  name: "tensor_95_odule/model/26/q_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2048
        }
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_96_odule/model/26/q_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_97_odule/model/26/q_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/q_proj/fp8_gemm_bf16/13088"
  op: "fp8_gemm_bf16"
  input: "module/model/26/q_proj/quant_input_0/convert_to_fp8_bf16/13087"
  input: "tensor_95_odule/model/26/q_proj/placeholder/1"
  input: "tensor_96_odule/model/26/q_proj/placeholder/2"
  input: "tensor_97_odule/model/26/q_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "28"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_94  |  Sizes = [1,189,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [1548288, 1548288, 8192, 1]  |  data = 0, sizeInBytes = 1548288  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_95_odule/model/26/q_proj/placeholder/1  |  Sizes = [8192,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16777216, 2048, 1]  |  data = 0, sizeInBytes = 16777216  |  isPersistent  |  userMemorySection(type=Persistent, id=33)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_96_odule/model/26/q_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db763f5a28, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=34)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_97_odule/model/26/q_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db6cb6f058, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=35)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_99  |  Sizes = [1,189,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
}
node {
  name: "module/model/26/reshape/13089"
  op: "Reshape"
  input: "module/model/26/q_proj/fp8_gemm_bf16/13088"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "29"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_99  |  Sizes = [1,189,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_100_id_126825_module/model/26/aten__view  |  Sizes = [1,189,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
}
node {
  name: "tensor_42_odule/model/26/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/quant_input_0/convert_to_fp8_bf16/13065"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/rotary_pos_embedding_fwd_bf16/13064"
  input: "tensor_42_odule/model/26/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "30"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_42_odule/model/26/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db7a828c60, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=16)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "tensor_65_odule/model/26/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/quant_input_0/convert_to_fp8_bf16/13073"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/quant_input_0/transpose/13072"
  input: "tensor_65_odule/model/26/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "31"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_64_id_126835_module/model/26/quant_input_0/aten__transpose  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_65_odule/model/26/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db860a5208, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=25)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_68  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/slice/13078"
  op: "Slice"
  input: "module/model/26/fused_scaled_dot_product_attention/expand_dims/13077"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "32"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_75_id_126721_module/model/26/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_76_id_126722_module/model/26/fused_scaled_dot_product_attention/aten__slice  |  Sizes = [1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
}
node {
  name: "module/model/26/transpose/13090"
  op: "Transpose"
  input: "module/model/26/reshape/13089"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "33"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_100_id_126825_module/model/26/aten__view  |  Sizes = [1,189,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_101_id_126827_module/model/26/aten__transpose  |  Sizes = [1,16,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 48384, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
}
node {
  name: "tensor_47_odule/model/26/quant_output/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/quant_output/convert_from_fp8_bf16/13067"
  op: "convert_from_fp8_bf16"
  input: "module/model/26/quant_input_0/convert_to_fp8_bf16/13065"
  input: "tensor_47_odule/model/26/quant_output/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "34"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_47_odule/model/26/quant_output/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db6bf5ed68, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=17)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  isPersistent  |  userMemorySection(type=Persistent, id=19)  |  "
    }
  }
}
node {
  name: "tensor_70_odule/model/26/quant_output/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/quant_output/convert_from_fp8_bf16/13075"
  op: "convert_from_fp8_bf16"
  input: "module/model/26/quant_input_0/convert_to_fp8_bf16/13073"
  input: "tensor_70_odule/model/26/quant_output/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "35"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_68  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_70_odule/model/26/quant_output/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db6020b138, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=26)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_72  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  isPersistent  |  userMemorySection(type=Persistent, id=28)  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/slice/13079"
  op: "Slice"
  input: "module/model/26/fused_scaled_dot_product_attention/slice/13078"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "36"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_76_id_126722_module/model/26/fused_scaled_dot_product_attention/aten__slice  |  Sizes = [1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_77_id_126723_module/model/26/fused_scaled_dot_product_attention/aten__slice  |  Sizes = [1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
}
node {
  name: "module/model/26/rotary_pos_embedding_fwd_bf16/13091"
  op: "rotary_pos_embedding_fwd_bf16"
  input: "module/model/26/transpose/13090"
  input: "module/model/26/identity/13058"
  input: "module/model/26/identity/13052"
  input: "module/model/26/expand_dims/13086"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "37"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_101_id_126827_module/model/26/aten__transpose  |  Sizes = [1,16,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 48384, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_23_id_126871_module/model/26/aten__clone  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_16_id_126865_module/model/26/aten__clone  |  Sizes = [1,1,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 48384, 256, 2]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_90_id_126719_module/model/26/aten__unsqueeze  |  Sizes = [1,189]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [756, 756, 4]  |  data = 0, sizeInBytes = 756  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_103  |  Sizes = [1,16,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 48384, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/broadcast/13080"
  op: "Broadcast"
  input: "module/model/26/fused_scaled_dot_product_attention/slice/13079"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "38"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_77_id_126723_module/model/26/fused_scaled_dot_product_attention/aten__slice  |  Sizes = [1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_78_id_126724_module/model/26/fused_scaled_dot_product_attention/hpu__expand  |  Sizes = [1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/expand_dims/13081"
  op: "ExpandDims"
  input: "module/model/26/fused_scaled_dot_product_attention/broadcast/13080"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "39"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_78_id_126724_module/model/26/fused_scaled_dot_product_attention/hpu__expand  |  Sizes = [1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_79_id_126946_module/model/26/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
}
node {
  name: "tensor_80_odule/model/26/fused_scaled_dot_product_attention/quant_v/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/quant_v/convert_to_fp8_bf16/13082"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/quant_output/convert_from_fp8_bf16/13075"
  input: "tensor_80_odule/model/26/fused_scaled_dot_product_attention/quant_v/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_72  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  isPersistent  |  userMemorySection(type=Persistent, id=28)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_80_odule/model/26/fused_scaled_dot_product_attention/quant_v/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db635b9ae8, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=30)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_83  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/reshape/13083"
  op: "Reshape"
  input: "module/model/26/fused_scaled_dot_product_attention/quant_v/convert_to_fp8_bf16/13082"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "41"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_83  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_84_id_126944_module/model/26/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,1,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "tensor_85_odule/model/26/fused_scaled_dot_product_attention/quant_k/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/quant_k/convert_to_fp8_bf16/13084"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/quant_output/convert_from_fp8_bf16/13067"
  input: "tensor_85_odule/model/26/fused_scaled_dot_product_attention/quant_k/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "42"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49  |  Sizes = [1,2,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [96768, 96768, 48384, 256, 2]  |  data = 0, sizeInBytes = 96768  |  isPersistent  |  userMemorySection(type=Persistent, id=19)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_85_odule/model/26/fused_scaled_dot_product_attention/quant_k/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db64582250, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=31)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_88  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/reshape/13085"
  op: "Reshape"
  input: "module/model/26/fused_scaled_dot_product_attention/quant_k/convert_to_fp8_bf16/13084"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "43"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_88  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_89_id_126942_module/model/26/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,1,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
}
node {
  name: "tensor_104_odule/model/26/fused_scaled_dot_product_attention/quant_q/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/quant_q/convert_to_fp8_bf16/13092"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/rotary_pos_embedding_fwd_bf16/13091"
  input: "tensor_104_odule/model/26/fused_scaled_dot_product_attention/quant_q/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "44"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_103  |  Sizes = [1,16,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 48384, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_104_odule/model/26/fused_scaled_dot_product_attention/quant_q/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db68fe82b8, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=36)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_107  |  Sizes = [1,16,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 24192, 128, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/reshape/13093"
  op: "Reshape"
  input: "module/model/26/fused_scaled_dot_product_attention/quant_q/convert_to_fp8_bf16/13092"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "45"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_107  |  Sizes = [1,16,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 24192, 128, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_108_id_126940_module/model/26/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,8,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 193536, 24192, 128, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
}
node {
  name: "tensor_109_odule/model/26/fused_scaled_dot_product_attention/placeholder/4"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_110_odule/model/26/fused_scaled_dot_product_attention/placeholder/5"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_111_odule/model/26/fused_scaled_dot_product_attention/placeholder/6"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_112_odule/model/26/fused_scaled_dot_product_attention/placeholder/7"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_113_odule/model/26/fused_scaled_dot_product_attention/placeholder/8"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_114_odule/model/26/fused_scaled_dot_product_attention/placeholder/9"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/13094"
  op: "sdpa_recomp_fwd_hf8"
  input: "module/model/26/fused_scaled_dot_product_attention/reshape/13093"
  input: "module/model/26/fused_scaled_dot_product_attention/reshape/13085"
  input: "module/model/26/fused_scaled_dot_product_attention/reshape/13083"
  input: "module/model/26/fused_scaled_dot_product_attention/expand_dims/13081"
  input: "unused_port"
  input: "tensor_109_odule/model/26/fused_scaled_dot_product_attention/placeholder/4"
  input: "tensor_110_odule/model/26/fused_scaled_dot_product_attention/placeholder/5"
  input: "tensor_111_odule/model/26/fused_scaled_dot_product_attention/placeholder/6"
  input: "tensor_112_odule/model/26/fused_scaled_dot_product_attention/placeholder/7"
  input: "tensor_113_odule/model/26/fused_scaled_dot_product_attention/placeholder/8"
  input: "tensor_114_odule/model/26/fused_scaled_dot_product_attention/placeholder/9"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "46"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:00"
    value {
      s: "tensor_108_id_126940_module/model/26/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,8,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 193536, 24192, 128, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
  attr {
    key: "inputTensor:01"
    value {
      s: "tensor_89_id_126942_module/model/26/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,1,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:02"
    value {
      s: "tensor_84_id_126944_module/model/26/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,1,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "inputTensor:03"
    value {
      s: "tensor_79_id_126946_module/model/26/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,1,189,189]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [71442, 71442, 71442, 71442, 378, 2]  |  data = 0, sizeInBytes = 71442  |  "
    }
  }
  attr {
    key: "inputTensor:05"
    value {
      s: "tensor_109_odule/model/26/fused_scaled_dot_product_attention/placeholder/4  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55db645823a0, sizeInBytes = 4  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=37)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:06"
    value {
      s: "tensor_110_odule/model/26/fused_scaled_dot_product_attention/placeholder/5  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55db645822f0, sizeInBytes = 4  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=38)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:07"
    value {
      s: "tensor_111_odule/model/26/fused_scaled_dot_product_attention/placeholder/6  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55db645821d0, sizeInBytes = 4  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=39)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:08"
    value {
      s: "tensor_112_odule/model/26/fused_scaled_dot_product_attention/placeholder/7  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55db645822d8, sizeInBytes = 4  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=40)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:09"
    value {
      s: "tensor_113_odule/model/26/fused_scaled_dot_product_attention/placeholder/8  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55db645822c8, sizeInBytes = 4  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=41)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:10"
    value {
      s: "tensor_114_odule/model/26/fused_scaled_dot_product_attention/placeholder/9  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55db64582278, sizeInBytes = 4  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=42)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_120  |  Sizes = [1,2,8,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 193536, 24192, 128, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/dequant_output/reshape/13095"
  op: "Reshape"
  input: "module/model/26/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/13094"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "47"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_120  |  Sizes = [1,2,8,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 193536, 24192, 128, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_121_id_126965_module/model/26/fused_scaled_dot_product_attention/dequant_output/aten__view  |  Sizes = [1,16,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 24192, 128, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
}
node {
  name: "tensor_122_odule/model/26/fused_scaled_dot_product_attention/dequant_output/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/fused_scaled_dot_product_attention/dequant_output/convert_from_fp8_bf16/13096"
  op: "convert_from_fp8_bf16"
  input: "module/model/26/fused_scaled_dot_product_attention/dequant_output/reshape/13095"
  input: "tensor_122_odule/model/26/fused_scaled_dot_product_attention/dequant_output/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "48"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_121_id_126965_module/model/26/fused_scaled_dot_product_attention/dequant_output/aten__view  |  Sizes = [1,16,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 24192, 128, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_122_odule/model/26/fused_scaled_dot_product_attention/dequant_output/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db6cb6e2f0, sizeInBytes = 2  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=43)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_124  |  Sizes = [1,16,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 48384, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
}
node {
  name: "module/model/26/transpose/13097"
  op: "Transpose"
  input: "module/model/26/fused_scaled_dot_product_attention/dequant_output/convert_from_fp8_bf16/13096"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "49"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_124  |  Sizes = [1,16,189,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 48384, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_125_id_126970_module/model/26/aten__transpose  |  Sizes = [1,189,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
}
node {
  name: "module/model/26/identity/13098"
  op: "Identity"
  input: "module/model/26/transpose/13097"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "50"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_125_id_126970_module/model/26/aten__transpose  |  Sizes = [1,189,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_126_id_126972_module/model/26/aten__clone  |  Sizes = [1,189,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
}
node {
  name: "module/model/26/o_proj/quant_input_0/reshape/13099"
  op: "Reshape"
  input: "module/model/26/identity/13098"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "51"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_126_id_126972_module/model/26/aten__clone  |  Sizes = [1,189,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 256, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_127_id_126975_module/model/26/o_proj/quant_input_0/aten__view  |  Sizes = [1,189,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
}
node {
  name: "module/model/26/constant_hf8/13045"
  op: "constant_hf8"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "52"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_5  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_5"
  op: "OutputTensor"
  input: "module/model/26/constant_hf8/13045"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 189
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/26/constant_hf8/13068"
  op: "constant_hf8"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "53"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_52  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  isPersistent  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_52"
  op: "OutputTensor"
  input: "module/model/26/constant_hf8/13068"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 189
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_128_odule/model/26/o_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/o_proj/quant_input_0/convert_to_fp8_bf16/13100"
  op: "convert_to_fp8_bf16"
  input: "module/model/26/o_proj/quant_input_0/reshape/13099"
  input: "tensor_128_odule/model/26/o_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "54"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_127_id_126975_module/model/26/o_proj/quant_input_0/aten__view  |  Sizes = [1,189,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [774144, 774144, 4096, 2]  |  data = 0, sizeInBytes = 774144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_128_odule/model/26/o_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db645820a8, sizeInBytes = 2  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=44)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_131  |  Sizes = [1,189,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 2048, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
}
node {
  name: "module/model/26/memcpy/13066"
  op: "Memcpy"
  input: "module/model/26/quant_input_0/convert_to_fp8_bf16/13065"
  input: "^module/model/26/constant_hf8/13045"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "55"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_46  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_46"
  op: "OutputTensor"
  input: "module/model/26/memcpy/13066"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 189
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/26/memcpy/13074"
  op: "Memcpy"
  input: "module/model/26/quant_input_0/convert_to_fp8_bf16/13073"
  input: "^module/model/26/constant_hf8/13068"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "56"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_68  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_69  |  Sizes = [1,2,189,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [48384, 48384, 24192, 128, 1]  |  data = 0, sizeInBytes = 48384  |  isPersistent  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_69"
  op: "OutputTensor"
  input: "module/model/26/memcpy/13074"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 189
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_132_odule/model/26/o_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 2048
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_133_odule/model/26/o_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_134_odule/model/26/o_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/26/o_proj/fp8_gemm_bf16/13101"
  op: "fp8_gemm_bf16"
  input: "module/model/26/o_proj/quant_input_0/convert_to_fp8_bf16/13100"
  input: "tensor_132_odule/model/26/o_proj/placeholder/1"
  input: "tensor_133_odule/model/26/o_proj/placeholder/2"
  input: "tensor_134_odule/model/26/o_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "57"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_131  |  Sizes = [1,189,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [387072, 387072, 2048, 1]  |  data = 0, sizeInBytes = 387072  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_132_odule/model/26/o_proj/placeholder/1  |  Sizes = [2048,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16777216, 8192, 1]  |  data = 0, sizeInBytes = 16777216  |  isPersistent  |  userMemorySection(type=Persistent, id=45)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_133_odule/model/26/o_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db645822f8, sizeInBytes = 2  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=46)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_134_odule/model/26/o_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55db64582308, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=47)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_136  |  Sizes = [1,189,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3096576, 3096576, 16384, 2]  |  data = 0, sizeInBytes = 3096576  |  isPersistent  |  userMemorySection(type=Persistent, id=49)  |  "
    }
  }
}
node {
  name: "tensor_136"
  op: "OutputTensor"
  input: "module/model/26/o_proj/fp8_gemm_bf16/13101"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 189
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
