node {
  name: "tensor_5_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "/reshape/232"
  op: "Reshape"
  input: "tensor_5_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_5_/placeholder/0  |  Sizes = [1,1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_7_tensor_5_/placeholder/0  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/reduce_max_fwd_bf16/233"
  op: "reduce_max_fwd_bf16"
  input: "/reshape/232"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7_tensor_5_/placeholder/0  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_9  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "/reshape/234"
  op: "Reshape"
  input: "/reduce_max_fwd_bf16/233"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_8  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6_id_4398_aten__max  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/reshape/235"
  op: "Reshape"
  input: "/reduce_max_fwd_bf16/233"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10_tensor_9  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_10_tensor_9"
  op: "OutputTensor"
  input: "/reshape/235"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "tensor_11_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "/cast_f32_to_bf16/236"
  op: "cast_f32_to_bf16"
  input: "tensor_11_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_/placeholder/1  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/div_bf16/237"
  op: "div_bf16"
  input: "/reshape/234"
  input: "/cast_f32_to_bf16/236"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6_id_4398_aten__max  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_4400_aten__div  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/log2_fwd_bf16/238"
  op: "log2_fwd_bf16"
  input: "/div_bf16/237"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_4400_aten__div  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_14_id_4402_aten__log2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/constant_i32/240"
  op: "constant_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "/ceil_fwd_bf16/239"
  op: "ceil_fwd_bf16"
  input: "/log2_fwd_bf16/238"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_14_id_4402_aten__log2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/cast_i32_to_bf16/241"
  op: "cast_i32_to_bf16"
  input: "/constant_i32/240"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_18  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_19  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/pow_fwd_bf16/242"
  op: "pow_fwd_bf16"
  input: "/cast_i32_to_bf16/241"
  input: "/ceil_fwd_bf16/239"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_19  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_16  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_17_id_4406_aten__pow  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/log2_fwd_bf16/243"
  op: "log2_fwd_bf16"
  input: "/pow_fwd_bf16/242"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17_id_4406_aten__pow  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_20_id_4409_aten__log2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "tensor_21_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "/cast_i32_to_bf16/244"
  op: "cast_i32_to_bf16"
  input: "tensor_21_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_21_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_23  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/div_bf16/245"
  op: "div_bf16"
  input: "/log2_fwd_bf16/243"
  input: "/cast_i32_to_bf16/244"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_20_id_4409_aten__log2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_23  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_22_id_4411_aten__div  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/ceil_fwd_bf16/246"
  op: "ceil_fwd_bf16"
  input: "/div_bf16/245"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_22_id_4411_aten__div  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_25  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/cast_i32_to_bf16/247"
  op: "cast_i32_to_bf16"
  input: "tensor_21_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_21_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/constant_i32/249"
  op: "constant_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_29  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "/mult_fwd_bf16/248"
  op: "mult_fwd_bf16"
  input: "/ceil_fwd_bf16/246"
  input: "/cast_i32_to_bf16/247"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_25  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_27  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_26_id_4415_aten__mul  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/cast_i32_to_bf16/250"
  op: "cast_i32_to_bf16"
  input: "/constant_i32/249"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_29  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_30  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/pow_fwd_bf16/251"
  op: "pow_fwd_bf16"
  input: "/cast_i32_to_bf16/250"
  input: "/mult_fwd_bf16/248"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_30  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_26_id_4415_aten__mul  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_28_id_4417_aten__pow  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "tensor_0_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "/reciprocal_fwd_bf16/229"
  op: "reciprocal_fwd_bf16"
  input: "tensor_0_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_/placeholder/0  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_1_id_4378_aten__reciprocal  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "tensor_2_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "/cast_i32_to_bf16/230"
  op: "cast_i32_to_bf16"
  input: "tensor_2_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_4  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "tensor_31_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "/max_fwd_bf16/252"
  op: "max_fwd_bf16"
  input: "/pow_fwd_bf16/251"
  input: "tensor_31_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_28_id_4417_aten__pow  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_31_/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_32_id_4424_aten__maximum  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "/mult_fwd_bf16/231"
  op: "mult_fwd_bf16"
  input: "/reciprocal_fwd_bf16/229"
  input: "/cast_i32_to_bf16/230"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_1_id_4378_aten__reciprocal  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_4  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_3_id_4380_aten__mul  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_3_id_4380_aten__mul"
  op: "OutputTensor"
  input: "/mult_fwd_bf16/231"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_33_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "/min_fwd_bf16/253"
  op: "min_fwd_bf16"
  input: "/max_fwd_bf16/252"
  input: "tensor_33_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_32_id_4424_aten__maximum  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_33_/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_34_id_4430_aten__minimum  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
}
node {
  name: "tensor_34_id_4430_aten__minimum"
  op: "OutputTensor"
  input: "/min_fwd_bf16/253"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
