node {
  name: "tensor_0_odule/model/27/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 32
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/27/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 32
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/27/add_fwd_bf16/13038"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/27/placeholder/0"
  input: "tensor_1_odule/model/27/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/27/placeholder/0  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/27/placeholder/1  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "tensor_3_odule/model/27/post_attention_layernorm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/27/post_attention_layernorm/rms_norm_ex_fwd_bf16/13039"
  op: "rms_norm_ex_fwd_bf16"
  input: "module/model/27/add_fwd_bf16/13038"
  input: "tensor_3_odule/model/27/post_attention_layernorm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_3_odule/model/27/post_attention_layernorm/placeholder/1  |  Sizes = [4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 2]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_7  |  Sizes = [1,32,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 128, 4, 4]  |  data = 0, sizeInBytes = 128  |  "
    }
  }
}
node {
  name: "tensor_7"
  op: "OutputTensor"
  input: "module/model/27/post_attention_layernorm/rms_norm_ex_fwd_bf16/13039"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 32
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_17_odule/model/27/gate_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/27/gate_proj/quant_input_0/convert_to_fp8_bf16/13042"
  op: "convert_to_fp8_bf16"
  input: "module/model/27/post_attention_layernorm/rms_norm_ex_fwd_bf16/13039"
  input: "tensor_17_odule/model/27/gate_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_17_odule/model/27/gate_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d665dbf98, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_20  |  Sizes = [1,32,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 4096, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "tensor_8_odule/model/27/up_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/27/up_proj/quant_input_0/convert_to_fp8_bf16/13040"
  op: "convert_to_fp8_bf16"
  input: "module/model/27/post_attention_layernorm/rms_norm_ex_fwd_bf16/13039"
  input: "tensor_8_odule/model/27/up_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_8_odule/model/27/up_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d664f9030, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11  |  Sizes = [1,32,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 4096, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "tensor_21_odule/model/27/gate_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 7168
        }
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_22_odule/model/27/gate_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_23_odule/model/27/gate_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/27/gate_proj/fp8_gemm_bf16/13043"
  op: "fp8_gemm_bf16"
  input: "module/model/27/gate_proj/quant_input_0/convert_to_fp8_bf16/13042"
  input: "tensor_21_odule/model/27/gate_proj/placeholder/1"
  input: "tensor_22_odule/model/27/gate_proj/placeholder/2"
  input: "tensor_23_odule/model/27/gate_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_20  |  Sizes = [1,32,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 4096, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_21_odule/model/27/gate_proj/placeholder/1  |  Sizes = [4096,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [29360128, 7168, 1]  |  data = 0, sizeInBytes = 29360128  |  isPersistent  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_22_odule/model/27/gate_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d665dbbf0, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=13)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_23_odule/model/27/gate_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d665dac58, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=14)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_25  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "tensor_12_odule/model/27/up_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 7168
        }
        dim {
          size: 4096
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_13_odule/model/27/up_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_14_odule/model/27/up_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/27/up_proj/fp8_gemm_bf16/13041"
  op: "fp8_gemm_bf16"
  input: "module/model/27/up_proj/quant_input_0/convert_to_fp8_bf16/13040"
  input: "tensor_12_odule/model/27/up_proj/placeholder/1"
  input: "tensor_13_odule/model/27/up_proj/placeholder/2"
  input: "tensor_14_odule/model/27/up_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11  |  Sizes = [1,32,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 4096, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_12_odule/model/27/up_proj/placeholder/1  |  Sizes = [4096,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [29360128, 7168, 1]  |  data = 0, sizeInBytes = 29360128  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_13_odule/model/27/up_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d665da798, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_14_odule/model/27/up_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d665db798, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=10)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/27/act_fn/silu_fwd_bf16/13044"
  op: "silu_fwd_bf16"
  input: "module/model/27/gate_proj/fp8_gemm_bf16/13043"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_25  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_26_id_46757_module/model/27/act_fn/aten__silu  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "module/model/27/mult_fwd_bf16/13045"
  op: "mult_fwd_bf16"
  input: "module/model/27/act_fn/silu_fwd_bf16/13044"
  input: "module/model/27/up_proj/fp8_gemm_bf16/13041"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_26_id_46757_module/model/27/act_fn/aten__silu  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_16  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_27_id_46772_module/model/27/aten__mul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
}
node {
  name: "tensor_28_odule/model/27/down_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/27/down_proj/quant_input_0/convert_to_fp8_bf16/13046"
  op: "convert_to_fp8_bf16"
  input: "module/model/27/mult_fwd_bf16/13045"
  input: "tensor_28_odule/model/27/down_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27_id_46772_module/model/27/aten__mul  |  Sizes = [1,32,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [458752, 458752, 14336, 2]  |  data = 0, sizeInBytes = 458752  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_28_odule/model/27/down_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d60fe8100, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=15)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_31  |  Sizes = [1,32,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [229376, 229376, 7168, 1]  |  data = 0, sizeInBytes = 229376  |  "
    }
  }
}
node {
  name: "tensor_32_odule/model/27/down_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 7168
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_33_odule/model/27/down_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_34_odule/model/27/down_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/27/down_proj/fp8_gemm_bf16/13047"
  op: "fp8_gemm_bf16"
  input: "module/model/27/down_proj/quant_input_0/convert_to_fp8_bf16/13046"
  input: "tensor_32_odule/model/27/down_proj/placeholder/1"
  input: "tensor_33_odule/model/27/down_proj/placeholder/2"
  input: "tensor_34_odule/model/27/down_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_31  |  Sizes = [1,32,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [229376, 229376, 7168, 1]  |  data = 0, sizeInBytes = 229376  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_32_odule/model/27/down_proj/placeholder/1  |  Sizes = [7168,4096]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [29360128, 4096, 1]  |  data = 0, sizeInBytes = 29360128  |  isPersistent  |  userMemorySection(type=Persistent, id=16)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_33_odule/model/27/down_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d635c7c78, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=17)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_34_odule/model/27/down_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x561d6219adf8, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=18)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_36  |  Sizes = [1,32,4096]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 8192, 2]  |  data = 0, sizeInBytes = 262144  |  isPersistent  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_36"
  op: "OutputTensor"
  input: "module/model/27/down_proj/fp8_gemm_bf16/13047"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 4096
        }
        dim {
          size: 32
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
