node {
  name: "tensor_12_odule/model/6/up_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 7168
        }
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/6/up_proj/fp8_gemm_bf16/6285_complex/fp8_gemm_bf16_107/expand_dims_6"
  op: "ExpandDims"
  input: "tensor_12_odule/model/6/up_proj/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_odule/model/6/up_proj/placeholder/1  |  Sizes = [8192,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 7168, 1]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "hf8-7_22757  |  Sizes = [1,8192,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 58720256, 7168, 1]  |  data = 0, sizeInBytes = 58720256  |  isAliased = tensor_12_odule/model/6/up_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_21_odule/model/6/gate_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 7168
        }
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/6/gate_proj/fp8_gemm_bf16/6287_complex/fp8_gemm_bf16_109/expand_dims_6"
  op: "ExpandDims"
  input: "tensor_21_odule/model/6/gate_proj/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_21_odule/model/6/gate_proj/placeholder/1  |  Sizes = [8192,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 7168, 1]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xc0000000000  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "hf8-7_22761  |  Sizes = [1,8192,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 58720256, 7168, 1]  |  data = 0, sizeInBytes = 58720256  |  isAliased = tensor_21_odule/model/6/gate_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_0_odule/model/6/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/6/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/6/add_fwd_bf16/6282_complex/add_fwd_bf16_0_bundle_40/op_0"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/6/placeholder/0"
  input: "tensor_1_odule/model/6/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/6/placeholder/0  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/6/placeholder/1  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_40_22964  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
}
node {
  name: "module/model/6/post_attention_layernorm/rms_norm_ex_fwd_bf16/6283_complex/rms_norm_ex_fwd_bf16_27/reshape_4_bundle_40/op_1"
  op: "Reshape"
  input: "module/model/6/add_fwd_bf16/6282_complex/add_fwd_bf16_0_bundle_40/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_40_22964  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-5_22750_slice_0_0_0_0_0__0__bundle_40_22965  |  Sizes = [284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  isAliased = tensor_2_slice_0_0_0_0_0__0__bundle_40_22964, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
}
node {
  name: "tensor_3_odule/model/6/post_attention_layernorm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/6/post_attention_layernorm/rms_norm_ex_fwd_bf16/6283_complex/rms_norm_ex_fwd_bf16_27/rms_norm_fwd_bf16_6_bundle_40/op_2"
  op: "rms_norm_fwd_bf16"
  input: "module/model/6/post_attention_layernorm/rms_norm_ex_fwd_bf16/6283_complex/rms_norm_ex_fwd_bf16_27/reshape_4_bundle_40/op_1"
  input: "tensor_3_odule/model/6/post_attention_layernorm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-5_22750_slice_0_0_0_0_0__0__bundle_40_22965  |  Sizes = [284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  isAliased = tensor_2_slice_0_0_0_0_0__0__bundle_40_22964, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_3_odule/model/6/post_attention_layernorm/placeholder/1  |  Sizes = [8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 2]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-7_22751_slice_0_0_0_0_0__0__bundle_40_22967  |  Sizes = [284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  isAliased = tensor-22942_slice_0_0_0_0_0__0__bundle_40_22969, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd4c0000  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "f32-8_22752  |  Sizes = [284,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1136, 4, 4]  |  data = 0, sizeInBytes = 1136  |  location = in DRAM  |  dramOffset = 0x140000000000  |  "
    }
  }
}
node {
  name: "f32-8_22752"
  op: "OutputTensor"
  input: "module/model/6/post_attention_layernorm/rms_norm_ex_fwd_bf16/6283_complex/rms_norm_ex_fwd_bf16_27/rms_norm_fwd_bf16_6_bundle_40/op_2"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "reshape_0_0_bundle_40/op_3"
  op: "Reshape"
  input: "module/model/6/post_attention_layernorm/rms_norm_ex_fwd_bf16/6283_complex/rms_norm_ex_fwd_bf16_27/rms_norm_fwd_bf16_6_bundle_40/op_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-7_22751_slice_0_0_0_0_0__0__bundle_40_22967  |  Sizes = [284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  isAliased = tensor-22942_slice_0_0_0_0_0__0__bundle_40_22969, type = alias, offset: 0  |  location = in SRAM  |  sramOffset = 0x1000fffffd4c0000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-22942_slice_0_0_0_0_0__0__bundle_40_22969  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  location = in SRAM  |  sramOffset = 0x1000fffffd4c0000  |  "
    }
  }
}
node {
  name: "fusedTPCNode_23_0_bundle_40/op_4"
  op: "fused_kernel_0x267DF148_34_bf16"
  input: "reshape_0_0_bundle_40/op_3"
  attr {
    key: "Bundle_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-22942_slice_0_0_0_0_0__0__bundle_40_22969  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  location = in SRAM  |  sramOffset = 0x1000fffffd4c0000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11_slice_0_0_0_0_0__0__bundle_40_22970  |  Sizes = [1,284,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 1]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd930000  |  "
    }
  }
}
node {
  name: "module/model/6/up_proj/fp8_gemm_bf16/6285_complex/fp8_gemm_bf16_107/batch_gemm_8_bundle_40/op_5_gemm"
  op: "GEMM"
  input: "fusedTPCNode_23_0_bundle_40/op_4"
  input: "module/model/6/up_proj/fp8_gemm_bf16/6285_complex/fp8_gemm_bf16_107/expand_dims_6"
  attr {
    key: "Bundle_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "11"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "15"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_slice_0_0_0_0_0__0__bundle_40_22970  |  Sizes = [1,284,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 1]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd930000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "hf8-7_22757  |  Sizes = [1,8192,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 58720256, 7168, 1]  |  data = 0, sizeInBytes = 58720256  |  isAliased = tensor_12_odule/model/6/up_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x140000000480  |  "
    }
  }
}
node {
  name: "module/model/6/gate_proj/fp8_gemm_bf16/6287_complex/fp8_gemm_bf16_109/batch_gemm_8_bundle_40/op_6_gemm"
  op: "GEMM"
  input: "fusedTPCNode_23_0_bundle_40/op_4"
  input: "module/model/6/gate_proj/fp8_gemm_bf16/6287_complex/fp8_gemm_bf16_109/expand_dims_6"
  attr {
    key: "Bundle_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "11"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "15"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_slice_0_0_0_0_0__0__bundle_40_22970  |  Sizes = [1,284,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2326528, 2326528, 8192, 1]  |  data = 0, sizeInBytes = 2326528  |  location = in SRAM  |  sramOffset = 0x1000fffffd930000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "hf8-7_22761  |  Sizes = [1,8192,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 58720256, 7168, 1]  |  data = 0, sizeInBytes = 58720256  |  isAliased = tensor_21_odule/model/6/gate_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_25  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "tensor_2_bundle_40/memcpy/0"
  op: "DmaMemcpy"
  input: "module/model/6/add_fwd_bf16/6282_complex/add_fwd_bf16_0_bundle_40/op_0"
  input: "^module/model/6/add_fwd_bf16/6282_complex/add_fwd_bf16_0_bundle_40/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_slice_0_0_0_0_0__0__bundle_40_22964  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "tensor_2"
  op: "OutputTensor"
  input: "tensor_2_bundle_40/memcpy/0"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_32_odule/model/6/down_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 7168
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/6/down_proj/fp8_gemm_bf16/6291_complex/fp8_gemm_bf16_111/expand_dims_6"
  op: "ExpandDims"
  input: "tensor_32_odule/model/6/down_proj/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_32_odule/model/6/down_proj/placeholder/1  |  Sizes = [7168,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 8192, 1]  |  data = 0, sizeInBytes = 58720256  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x100000000000  |  userMemorySection(type=Persistent, id=16)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "hf8-7_22770  |  Sizes = [1,7168,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 58720256, 8192, 1]  |  data = 0, sizeInBytes = 58720256  |  isAliased = tensor_32_odule/model/6/down_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "fusedTPCNode_23_1_bundle_41/op_0"
  op: "fused_kernel_0xE63D8ECD_35_bf16"
  input: "module/model/6/gate_proj/fp8_gemm_bf16/6287_complex/fp8_gemm_bf16_109/batch_gemm_8_bundle_40/op_6_gemm"
  input: "module/model/6/up_proj/fp8_gemm_bf16/6285_complex/fp8_gemm_bf16_107/batch_gemm_8_bundle_40/op_5_gemm"
  attr {
    key: "Bundle_idx"
    value {
      s: "41"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_25  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_16  |  Sizes = [1,284,7168]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4071424, 4071424, 14336, 2]  |  data = 0, sizeInBytes = 4071424  |  location = in DRAM  |  dramOffset = 0x140000000480  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_31_slice_0_0_0_0_0__0__bundle_41_22980  |  Sizes = [1,284,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2035712, 2035712, 7168, 1]  |  data = 0, sizeInBytes = 2035712  |  location = in SRAM  |  sramOffset = 0x1000fffffdb68000  |  "
    }
  }
}
node {
  name: "module/model/6/down_proj/fp8_gemm_bf16/6291_complex/fp8_gemm_bf16_111/batch_gemm_8_bundle_41/op_1_gemm"
  op: "GEMM"
  input: "fusedTPCNode_23_1_bundle_41/op_0"
  input: "module/model/6/down_proj/fp8_gemm_bf16/6291_complex/fp8_gemm_bf16_111/expand_dims_6"
  attr {
    key: "Bundle_idx"
    value {
      s: "41"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=false"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "11"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "15"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_31_slice_0_0_0_0_0__0__bundle_41_22980  |  Sizes = [1,284,7168]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2035712, 2035712, 7168, 1]  |  data = 0, sizeInBytes = 2035712  |  location = in SRAM  |  sramOffset = 0x1000fffffdb68000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "hf8-7_22770  |  Sizes = [1,7168,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [58720256, 58720256, 8192, 1]  |  data = 0, sizeInBytes = 58720256  |  isAliased = tensor_32_odule/model/6/down_proj/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_36  |  Sizes = [1,284,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4653056, 4653056, 16384, 2]  |  data = 0, sizeInBytes = 4653056  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x140000000000  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_36"
  op: "OutputTensor"
  input: "module/model/6/down_proj/fp8_gemm_bf16/6291_complex/fp8_gemm_bf16_111/batch_gemm_8_bundle_41/op_1_gemm"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 284
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
