node {
  name: "tensor_7_odule/model/10/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "module/model/10/expand_dims/17751"
  op: "ExpandDims"
  input: "tensor_7_odule/model/10/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7_odule/model/10/placeholder/0  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8_id_249424_module/model/10/aten__unsqueeze/1  |  Sizes = [1,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 256, 4]  |  data = 0, sizeInBytes = 256  |  "
    }
  }
}
node {
  name: "tensor_73_odule/model/10/fused_scaled_dot_product_attention/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 64
        }
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/expand_dims/17781"
  op: "ExpandDims"
  input: "tensor_73_odule/model/10/fused_scaled_dot_product_attention/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_73_odule/model/10/fused_scaled_dot_product_attention/placeholder/0  |  Sizes = [64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  userMemorySection(type=Persistent, id=29)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_74_id_249425_module/model/10/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/expand_dims/17782"
  op: "ExpandDims"
  input: "module/model/10/fused_scaled_dot_product_attention/expand_dims/17781"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_74_id_249425_module/model/10/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_75_id_249426_module/model/10/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
}
node {
  name: "module/model/10/expand_dims/17791"
  op: "ExpandDims"
  input: "tensor_7_odule/model/10/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7_odule/model/10/placeholder/0  |  Sizes = [64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 4]  |  data = 0, sizeInBytes = 256  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_90_id_249424_module/model/10/aten__unsqueeze  |  Sizes = [1,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 256, 4]  |  data = 0, sizeInBytes = 256  |  "
    }
  }
}
node {
  name: "tensor_0_odule/model/9/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_1_odule/model/9/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/9/add_fwd_bf16/17749"
  op: "add_fwd_bf16"
  input: "tensor_0_odule/model/9/placeholder/0"
  input: "tensor_1_odule/model/9/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_odule/model/9/placeholder/0  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_odule/model/9/placeholder/1  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
}
node {
  name: "tensor_24_odule/model/10/input_layernorm/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/input_layernorm/rms_norm_ex_fwd_bf16/17764"
  op: "rms_norm_ex_fwd_bf16"
  input: "module/model/9/add_fwd_bf16/17749"
  input: "tensor_24_odule/model/10/input_layernorm/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_24_odule/model/10/input_layernorm/placeholder/1  |  Sizes = [8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 2]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_28  |  Sizes = [1,64,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 256, 4, 4]  |  data = 0, sizeInBytes = 256  |  "
    }
  }
}
node {
  name: "tensor_28"
  op: "OutputTensor"
  input: "module/model/10/input_layernorm/rms_norm_ex_fwd_bf16/17764"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_29_odule/model/10/k_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/k_proj/quant_input_0/convert_to_fp8_bf16/17765"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/input_layernorm/rms_norm_ex_fwd_bf16/17764"
  input: "tensor_29_odule/model/10/k_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_29_odule/model/10/k_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fdc8, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=12)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_32  |  Sizes = [1,64,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [524288, 524288, 8192, 1]  |  data = 0, sizeInBytes = 524288  |  "
    }
  }
}
node {
  name: "tensor_9_odule/model/10/rotary_emb/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 131072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/rotary_emb/slice/17752"
  op: "Slice"
  input: "tensor_9_odule/model/10/rotary_emb/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9_odule/model/10/rotary_emb/placeholder/0  |  Sizes = [131072,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 33554432  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10_id_249542_module/model/10/rotary_emb/aten__slice  |  Sizes = [64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "tensor_11_odule/model/10/rotary_emb/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/10/rotary_emb/cast_f32_to_bf16/17753"
  op: "cast_f32_to_bf16"
  input: "tensor_11_odule/model/10/rotary_emb/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_odule/model/10/rotary_emb/placeholder/1  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "tensor_17_odule/model/10/rotary_emb/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 131072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/rotary_emb/slice/17758"
  op: "Slice"
  input: "tensor_17_odule/model/10/rotary_emb/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17_odule/model/10/rotary_emb/placeholder/0  |  Sizes = [131072,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [33554432, 256, 2]  |  data = 0, sizeInBytes = 33554432  |  isPersistent  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18_id_249546_module/model/10/rotary_emb/aten__slice  |  Sizes = [64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/rotary_emb/cast_f32_to_bf16/17759"
  op: "cast_f32_to_bf16"
  input: "tensor_11_odule/model/10/rotary_emb/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_11_odule/model/10/rotary_emb/placeholder/1  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_20  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "tensor_33_odule/model/10/k_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_34_odule/model/10/k_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_35_odule/model/10/k_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/k_proj/fp8_gemm_bf16/17766"
  op: "fp8_gemm_bf16"
  input: "module/model/10/k_proj/quant_input_0/convert_to_fp8_bf16/17765"
  input: "tensor_33_odule/model/10/k_proj/placeholder/1"
  input: "tensor_34_odule/model/10/k_proj/placeholder/2"
  input: "tensor_35_odule/model/10/k_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_32  |  Sizes = [1,64,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [524288, 524288, 8192, 1]  |  data = 0, sizeInBytes = 524288  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_33_odule/model/10/k_proj/placeholder/1  |  Sizes = [8192,256]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 256, 1]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_34_odule/model/10/k_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fd70, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=14)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_35_odule/model/10/k_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fdb0, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=15)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [1,64,256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 512, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
}
node {
  name: "module/model/10/reshape/17767"
  op: "Reshape"
  input: "module/model/10/k_proj/fp8_gemm_bf16/17766"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [1,64,256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 512, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_38_id_249534_module/model/10/aten__view  |  Sizes = [1,64,2,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 512, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
}
node {
  name: "tensor_54_odule/model/10/v_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/v_proj/quant_input_0/convert_to_fp8_bf16/17774"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/input_layernorm/rms_norm_ex_fwd_bf16/17764"
  input: "tensor_54_odule/model/10/v_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_54_odule/model/10/v_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fb98, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=21)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_57  |  Sizes = [1,64,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [524288, 524288, 8192, 1]  |  data = 0, sizeInBytes = 524288  |  "
    }
  }
}
node {
  name: "module/model/10/rotary_emb/mult_fwd_bf16/17754"
  op: "mult_fwd_bf16"
  input: "module/model/10/rotary_emb/slice/17752"
  input: "module/model/10/rotary_emb/cast_f32_to_bf16/17753"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_10_id_249542_module/model/10/rotary_emb/aten__slice  |  Sizes = [64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_13  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_249544_module/model/10/rotary_emb/aten__mul  |  Sizes = [64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/expand_dims/17755"
  op: "ExpandDims"
  input: "module/model/10/rotary_emb/mult_fwd_bf16/17754"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_249544_module/model/10/rotary_emb/aten__mul  |  Sizes = [64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_14_id_249566_module/model/10/aten__unsqueeze  |  Sizes = [1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/expand_dims/17756"
  op: "ExpandDims"
  input: "module/model/10/expand_dims/17755"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_14_id_249566_module/model/10/aten__unsqueeze  |  Sizes = [1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_15_id_249568_module/model/10/aten__unsqueeze  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/identity/17757"
  op: "Identity"
  input: "module/model/10/expand_dims/17756"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_15_id_249568_module/model/10/aten__unsqueeze  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16_id_249570_module/model/10/aten__clone  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/rotary_emb/mult_fwd_bf16/17760"
  op: "mult_fwd_bf16"
  input: "module/model/10/rotary_emb/slice/17758"
  input: "module/model/10/rotary_emb/cast_f32_to_bf16/17759"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_18_id_249546_module/model/10/rotary_emb/aten__slice  |  Sizes = [64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_20  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_19_id_249548_module/model/10/rotary_emb/aten__mul  |  Sizes = [64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/expand_dims/17761"
  op: "ExpandDims"
  input: "module/model/10/rotary_emb/mult_fwd_bf16/17760"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_19_id_249548_module/model/10/rotary_emb/aten__mul  |  Sizes = [64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_21_id_249572_module/model/10/aten__unsqueeze  |  Sizes = [1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/expand_dims/17762"
  op: "ExpandDims"
  input: "module/model/10/expand_dims/17761"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_21_id_249572_module/model/10/aten__unsqueeze  |  Sizes = [1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_22_id_249574_module/model/10/aten__unsqueeze  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/identity/17763"
  op: "Identity"
  input: "module/model/10/expand_dims/17762"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_22_id_249574_module/model/10/aten__unsqueeze  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_23_id_249576_module/model/10/aten__clone  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/transpose/17768"
  op: "Transpose"
  input: "module/model/10/reshape/17767"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_38_id_249534_module/model/10/aten__view  |  Sizes = [1,64,2,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 512, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_39_id_249536_module/model/10/aten__transpose  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
}
node {
  name: "tensor_58_odule/model/10/v_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_59_odule/model/10/v_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_60_odule/model/10/v_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/v_proj/fp8_gemm_bf16/17775"
  op: "fp8_gemm_bf16"
  input: "module/model/10/v_proj/quant_input_0/convert_to_fp8_bf16/17774"
  input: "tensor_58_odule/model/10/v_proj/placeholder/1"
  input: "tensor_59_odule/model/10/v_proj/placeholder/2"
  input: "tensor_60_odule/model/10/v_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_57  |  Sizes = [1,64,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [524288, 524288, 8192, 1]  |  data = 0, sizeInBytes = 524288  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_58_odule/model/10/v_proj/placeholder/1  |  Sizes = [8192,256]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [2097152, 256, 1]  |  data = 0, sizeInBytes = 2097152  |  isPersistent  |  userMemorySection(type=Persistent, id=22)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_59_odule/model/10/v_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fb68, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=23)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_60_odule/model/10/v_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fb80, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=24)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_62  |  Sizes = [1,64,256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 512, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
}
node {
  name: "module/model/10/quant_input_0/reshape/17776"
  op: "Reshape"
  input: "module/model/10/v_proj/fp8_gemm_bf16/17775"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_62  |  Sizes = [1,64,256]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 512, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_63_id_249538_module/model/10/quant_input_0/aten__view  |  Sizes = [1,64,2,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 512, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
}
node {
  name: "tensor_91_odule/model/10/q_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/q_proj/quant_input_0/convert_to_fp8_bf16/17792"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/input_layernorm/rms_norm_ex_fwd_bf16/17764"
  input: "tensor_91_odule/model/10/q_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "25"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_91_odule/model/10/q_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd9f1aaf0, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=32)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_94  |  Sizes = [1,64,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [524288, 524288, 8192, 1]  |  data = 0, sizeInBytes = 524288  |  "
    }
  }
}
node {
  name: "module/model/10/rotary_pos_embedding_fwd_bf16/17769"
  op: "rotary_pos_embedding_fwd_bf16"
  input: "module/model/10/transpose/17768"
  input: "module/model/10/identity/17763"
  input: "module/model/10/identity/17757"
  input: "module/model/10/expand_dims/17751"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "26"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_39_id_249536_module/model/10/aten__transpose  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_23_id_249576_module/model/10/aten__clone  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_16_id_249570_module/model/10/aten__clone  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_8_id_249424_module/model/10/aten__unsqueeze/1  |  Sizes = [1,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 256, 4]  |  data = 0, sizeInBytes = 256  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
}
node {
  name: "module/model/10/quant_input_0/transpose/17777"
  op: "Transpose"
  input: "module/model/10/quant_input_0/reshape/17776"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "27"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_63_id_249538_module/model/10/quant_input_0/aten__view  |  Sizes = [1,64,2,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 512, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_64_id_249540_module/model/10/quant_input_0/aten__transpose  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
}
node {
  name: "tensor_95_odule/model/10/q_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2048
        }
        dim {
          size: 8192
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_96_odule/model/10/q_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_97_odule/model/10/q_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/q_proj/fp8_gemm_bf16/17793"
  op: "fp8_gemm_bf16"
  input: "module/model/10/q_proj/quant_input_0/convert_to_fp8_bf16/17792"
  input: "tensor_95_odule/model/10/q_proj/placeholder/1"
  input: "tensor_96_odule/model/10/q_proj/placeholder/2"
  input: "tensor_97_odule/model/10/q_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "28"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_94  |  Sizes = [1,64,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [524288, 524288, 8192, 1]  |  data = 0, sizeInBytes = 524288  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_95_odule/model/10/q_proj/placeholder/1  |  Sizes = [8192,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16777216, 2048, 1]  |  data = 0, sizeInBytes = 16777216  |  isPersistent  |  userMemorySection(type=Persistent, id=33)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_96_odule/model/10/q_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fae0, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=34)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_97_odule/model/10/q_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52faf8, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=35)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_99  |  Sizes = [1,64,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/10/reshape/17794"
  op: "Reshape"
  input: "module/model/10/q_proj/fp8_gemm_bf16/17793"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "29"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_99  |  Sizes = [1,64,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_100_id_249530_module/model/10/aten__view  |  Sizes = [1,64,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "tensor_42_odule/model/10/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/quant_input_0/convert_to_fp8_bf16/17770"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/rotary_pos_embedding_fwd_bf16/17769"
  input: "tensor_42_odule/model/10/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "30"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_41  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_42_odule/model/10/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fca8, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=16)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "tensor_65_odule/model/10/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/quant_input_0/convert_to_fp8_bf16/17778"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/quant_input_0/transpose/17777"
  input: "tensor_65_odule/model/10/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "31"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_64_id_249540_module/model/10/quant_input_0/aten__transpose  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_65_odule/model/10/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fb20, sizeInBytes = 2  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=25)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_68  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/slice/17783"
  op: "Slice"
  input: "module/model/10/fused_scaled_dot_product_attention/expand_dims/17782"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "32"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_75_id_249426_module/model/10/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_76_id_249427_module/model/10/fused_scaled_dot_product_attention/aten__slice  |  Sizes = [1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
}
node {
  name: "module/model/10/transpose/17795"
  op: "Transpose"
  input: "module/model/10/reshape/17794"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "33"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_100_id_249530_module/model/10/aten__view  |  Sizes = [1,64,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_101_id_249532_module/model/10/aten__transpose  |  Sizes = [1,16,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 16384, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "tensor_47_odule/model/10/quant_output/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/quant_output/convert_from_fp8_bf16/17772"
  op: "convert_from_fp8_bf16"
  input: "module/model/10/quant_input_0/convert_to_fp8_bf16/17770"
  input: "tensor_47_odule/model/10/quant_output/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "34"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_47_odule/model/10/quant_output/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52fc18, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=17)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  isPersistent  |  userMemorySection(type=Persistent, id=19)  |  "
    }
  }
}
node {
  name: "tensor_70_odule/model/10/quant_output/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/quant_output/convert_from_fp8_bf16/17780"
  op: "convert_from_fp8_bf16"
  input: "module/model/10/quant_input_0/convert_to_fp8_bf16/17778"
  input: "tensor_70_odule/model/10/quant_output/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "35"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_68  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_70_odule/model/10/quant_output/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd3c0a0a0, sizeInBytes = 2  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=26)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_72  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  isPersistent  |  userMemorySection(type=Persistent, id=28)  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/slice/17784"
  op: "Slice"
  input: "module/model/10/fused_scaled_dot_product_attention/slice/17783"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "36"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_76_id_249427_module/model/10/fused_scaled_dot_product_attention/aten__slice  |  Sizes = [1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_77_id_249428_module/model/10/fused_scaled_dot_product_attention/aten__slice  |  Sizes = [1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
}
node {
  name: "module/model/10/rotary_pos_embedding_fwd_bf16/17796"
  op: "rotary_pos_embedding_fwd_bf16"
  input: "module/model/10/transpose/17795"
  input: "module/model/10/identity/17763"
  input: "module/model/10/identity/17757"
  input: "module/model/10/expand_dims/17791"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "37"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_101_id_249532_module/model/10/aten__transpose  |  Sizes = [1,16,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 16384, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_23_id_249576_module/model/10/aten__clone  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_16_id_249570_module/model/10/aten__clone  |  Sizes = [1,1,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 16384, 256, 2]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_90_id_249424_module/model/10/aten__unsqueeze  |  Sizes = [1,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [256, 256, 4]  |  data = 0, sizeInBytes = 256  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_103  |  Sizes = [1,16,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 16384, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/broadcast/17785"
  op: "Broadcast"
  input: "module/model/10/fused_scaled_dot_product_attention/slice/17784"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "38"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_77_id_249428_module/model/10/fused_scaled_dot_product_attention/aten__slice  |  Sizes = [1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_78_id_249429_module/model/10/fused_scaled_dot_product_attention/hpu__expand  |  Sizes = [1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/expand_dims/17786"
  op: "ExpandDims"
  input: "module/model/10/fused_scaled_dot_product_attention/broadcast/17785"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "39"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_78_id_249429_module/model/10/fused_scaled_dot_product_attention/hpu__expand  |  Sizes = [1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_79_id_249651_module/model/10/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
}
node {
  name: "tensor_80_odule/model/10/fused_scaled_dot_product_attention/quant_v/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/quant_v/convert_to_fp8_bf16/17787"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/quant_output/convert_from_fp8_bf16/17780"
  input: "tensor_80_odule/model/10/fused_scaled_dot_product_attention/quant_v/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_72  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  isPersistent  |  userMemorySection(type=Persistent, id=28)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_80_odule/model/10/fused_scaled_dot_product_attention/quant_v/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52f1b0, sizeInBytes = 2  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=30)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_83  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/reshape/17788"
  op: "Reshape"
  input: "module/model/10/fused_scaled_dot_product_attention/quant_v/convert_to_fp8_bf16/17787"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "41"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_83  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_84_id_249649_module/model/10/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,1,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "tensor_85_odule/model/10/fused_scaled_dot_product_attention/quant_k/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/quant_k/convert_to_fp8_bf16/17789"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/quant_output/convert_from_fp8_bf16/17772"
  input: "tensor_85_odule/model/10/fused_scaled_dot_product_attention/quant_k/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "42"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49  |  Sizes = [1,2,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32768, 32768, 16384, 256, 2]  |  data = 0, sizeInBytes = 32768  |  isPersistent  |  userMemorySection(type=Persistent, id=19)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_85_odule/model/10/fused_scaled_dot_product_attention/quant_k/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd9e5f368, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=31)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_88  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/reshape/17790"
  op: "Reshape"
  input: "module/model/10/fused_scaled_dot_product_attention/quant_k/convert_to_fp8_bf16/17789"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "43"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_88  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_89_id_249647_module/model/10/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,1,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
}
node {
  name: "tensor_104_odule/model/10/fused_scaled_dot_product_attention/quant_q/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/quant_q/convert_to_fp8_bf16/17797"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/rotary_pos_embedding_fwd_bf16/17796"
  input: "tensor_104_odule/model/10/fused_scaled_dot_product_attention/quant_q/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "44"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_103  |  Sizes = [1,16,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 16384, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_104_odule/model/10/fused_scaled_dot_product_attention/quant_q/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afda52f348, sizeInBytes = 2  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=36)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_107  |  Sizes = [1,16,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 128, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/reshape/17798"
  op: "Reshape"
  input: "module/model/10/fused_scaled_dot_product_attention/quant_q/convert_to_fp8_bf16/17797"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "45"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_107  |  Sizes = [1,16,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 128, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_108_id_249645_module/model/10/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,8,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 65536, 8192, 128, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "tensor_109_odule/model/10/fused_scaled_dot_product_attention/placeholder/4"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_110_odule/model/10/fused_scaled_dot_product_attention/placeholder/5"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_111_odule/model/10/fused_scaled_dot_product_attention/placeholder/6"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_112_odule/model/10/fused_scaled_dot_product_attention/placeholder/7"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_113_odule/model/10/fused_scaled_dot_product_attention/placeholder/8"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_114_odule/model/10/fused_scaled_dot_product_attention/placeholder/9"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/17799"
  op: "sdpa_recomp_fwd_hf8"
  input: "module/model/10/fused_scaled_dot_product_attention/reshape/17798"
  input: "module/model/10/fused_scaled_dot_product_attention/reshape/17790"
  input: "module/model/10/fused_scaled_dot_product_attention/reshape/17788"
  input: "module/model/10/fused_scaled_dot_product_attention/expand_dims/17786"
  input: "unused_port"
  input: "tensor_109_odule/model/10/fused_scaled_dot_product_attention/placeholder/4"
  input: "tensor_110_odule/model/10/fused_scaled_dot_product_attention/placeholder/5"
  input: "tensor_111_odule/model/10/fused_scaled_dot_product_attention/placeholder/6"
  input: "tensor_112_odule/model/10/fused_scaled_dot_product_attention/placeholder/7"
  input: "tensor_113_odule/model/10/fused_scaled_dot_product_attention/placeholder/8"
  input: "tensor_114_odule/model/10/fused_scaled_dot_product_attention/placeholder/9"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "46"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:00"
    value {
      s: "tensor_108_id_249645_module/model/10/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,8,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 65536, 8192, 128, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "inputTensor:01"
    value {
      s: "tensor_89_id_249647_module/model/10/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,1,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:02"
    value {
      s: "tensor_84_id_249649_module/model/10/fused_scaled_dot_product_attention/aten__view  |  Sizes = [1,2,1,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "inputTensor:03"
    value {
      s: "tensor_79_id_249651_module/model/10/fused_scaled_dot_product_attention/aten__unsqueeze  |  Sizes = [1,1,1,64,64]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 8192, 8192, 8192, 128, 2]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
  attr {
    key: "inputTensor:05"
    value {
      s: "tensor_109_odule/model/10/fused_scaled_dot_product_attention/placeholder/4  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55afd8dca600, sizeInBytes = 4  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=37)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:06"
    value {
      s: "tensor_110_odule/model/10/fused_scaled_dot_product_attention/placeholder/5  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55afd7de61b8, sizeInBytes = 4  |  buffer = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=38)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:07"
    value {
      s: "tensor_111_odule/model/10/fused_scaled_dot_product_attention/placeholder/6  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55afd7de61b0, sizeInBytes = 4  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=39)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:08"
    value {
      s: "tensor_112_odule/model/10/fused_scaled_dot_product_attention/placeholder/7  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55afd7de61c0, sizeInBytes = 4  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=40)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:09"
    value {
      s: "tensor_113_odule/model/10/fused_scaled_dot_product_attention/placeholder/8  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55afd7de61c8, sizeInBytes = 4  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=41)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "inputTensor:10"
    value {
      s: "tensor_114_odule/model/10/fused_scaled_dot_product_attention/placeholder/9  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0x55afd7de61d0, sizeInBytes = 4  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=42)  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_120  |  Sizes = [1,2,8,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 65536, 8192, 128, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/dequant_output/reshape/17800"
  op: "Reshape"
  input: "module/model/10/fused_scaled_dot_product_attention/sdpa_recomp_fwd_hf8/17799"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "47"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_120  |  Sizes = [1,2,8,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 65536, 8192, 128, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_121_id_249670_module/model/10/fused_scaled_dot_product_attention/dequant_output/aten__view  |  Sizes = [1,16,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 128, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "tensor_122_odule/model/10/fused_scaled_dot_product_attention/dequant_output/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/fused_scaled_dot_product_attention/dequant_output/convert_from_fp8_bf16/17801"
  op: "convert_from_fp8_bf16"
  input: "module/model/10/fused_scaled_dot_product_attention/dequant_output/reshape/17800"
  input: "tensor_122_odule/model/10/fused_scaled_dot_product_attention/dequant_output/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "48"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_121_id_249670_module/model/10/fused_scaled_dot_product_attention/dequant_output/aten__view  |  Sizes = [1,16,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 8192, 128, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_122_odule/model/10/fused_scaled_dot_product_attention/dequant_output/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd7de61e0, sizeInBytes = 2  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=43)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_124  |  Sizes = [1,16,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 16384, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/10/transpose/17802"
  op: "Transpose"
  input: "module/model/10/fused_scaled_dot_product_attention/dequant_output/convert_from_fp8_bf16/17801"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "49"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "permutation: (0,2,1,3)"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_124  |  Sizes = [1,16,64,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 16384, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_125_id_249675_module/model/10/aten__transpose  |  Sizes = [1,64,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/10/identity/17803"
  op: "Identity"
  input: "module/model/10/transpose/17802"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "50"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_125_id_249675_module/model/10/aten__transpose  |  Sizes = [1,64,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_126_id_249677_module/model/10/aten__clone  |  Sizes = [1,64,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/10/o_proj/quant_input_0/reshape/17804"
  op: "Reshape"
  input: "module/model/10/identity/17803"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "51"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_126_id_249677_module/model/10/aten__clone  |  Sizes = [1,64,16,128]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 256, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_127_id_249680_module/model/10/o_proj/quant_input_0/aten__view  |  Sizes = [1,64,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
}
node {
  name: "module/model/10/constant_hf8/17750"
  op: "constant_hf8"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "52"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_5  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_5"
  op: "OutputTensor"
  input: "module/model/10/constant_hf8/17750"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 64
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/10/constant_hf8/17773"
  op: "constant_hf8"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "53"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_52  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_52"
  op: "OutputTensor"
  input: "module/model/10/constant_hf8/17773"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 64
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_128_odule/model/10/o_proj/quant_input_0/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/o_proj/quant_input_0/convert_to_fp8_bf16/17805"
  op: "convert_to_fp8_bf16"
  input: "module/model/10/o_proj/quant_input_0/reshape/17804"
  input: "tensor_128_odule/model/10/o_proj/quant_input_0/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "54"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_127_id_249680_module/model/10/o_proj/quant_input_0/aten__view  |  Sizes = [1,64,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [262144, 262144, 4096, 2]  |  data = 0, sizeInBytes = 262144  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_128_odule/model/10/o_proj/quant_input_0/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd7de6258, sizeInBytes = 2  |  buffer = 16  |  isPersistent  |  userMemorySection(type=Persistent, id=44)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_131  |  Sizes = [1,64,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 2048, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "module/model/10/memcpy/17771"
  op: "Memcpy"
  input: "module/model/10/quant_input_0/convert_to_fp8_bf16/17770"
  input: "^module/model/10/constant_hf8/17750"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "55"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_46  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_46"
  op: "OutputTensor"
  input: "module/model/10/memcpy/17771"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 64
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "module/model/10/memcpy/17779"
  op: "Memcpy"
  input: "module/model/10/quant_input_0/convert_to_fp8_bf16/17778"
  input: "^module/model/10/constant_hf8/17773"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "56"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_68  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_69  |  Sizes = [1,2,64,128]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16384, 16384, 8192, 128, 1]  |  data = 0, sizeInBytes = 16384  |  isPersistent  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_69"
  op: "OutputTensor"
  input: "module/model/10/memcpy/17779"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 128
        }
        dim {
          size: 64
        }
        dim {
          size: 2
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_132_odule/model/10/o_proj/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INVALID
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 2048
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "hfloat8"
    }
  }
}
node {
  name: "tensor_133_odule/model/10/o_proj/placeholder/2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_134_odule/model/10/o_proj/placeholder/3"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "module/model/10/o_proj/fp8_gemm_bf16/17806"
  op: "fp8_gemm_bf16"
  input: "module/model/10/o_proj/quant_input_0/convert_to_fp8_bf16/17805"
  input: "tensor_132_odule/model/10/o_proj/placeholder/1"
  input: "tensor_133_odule/model/10/o_proj/placeholder/2"
  input: "tensor_134_odule/model/10/o_proj/placeholder/3"
  input: "unused_port"
  input: "unused_port"
  input: "unused_port"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "57"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_131  |  Sizes = [1,64,2048]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 131072, 2048, 1]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_132_odule/model/10/o_proj/placeholder/1  |  Sizes = [2048,8192]  |  hfloat8  |  expBias = 7, scale = 1  |    |  ModelParam = 0  |  strides = [16777216, 8192, 1]  |  data = 0, sizeInBytes = 16777216  |  isPersistent  |  userMemorySection(type=Persistent, id=45)  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_133_odule/model/10/o_proj/placeholder/2  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd7de6288, sizeInBytes = 2  |  buffer = 0.0625  |  isPersistent  |  userMemorySection(type=Persistent, id=46)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "inputTensor:3"
    value {
      s: "tensor_134_odule/model/10/o_proj/placeholder/3  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0x55afd7de6280, sizeInBytes = 2  |  buffer = 0.00390625  |  isPersistent  |  userMemorySection(type=Persistent, id=47)  |  isStaticParam  |  bufferDtype=bf16  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_136  |  Sizes = [1,64,8192]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1048576, 1048576, 16384, 2]  |  data = 0, sizeInBytes = 1048576  |  isPersistent  |  userMemorySection(type=Persistent, id=49)  |  "
    }
  }
}
node {
  name: "tensor_136"
  op: "OutputTensor"
  input: "module/model/10/o_proj/fp8_gemm_bf16/17806"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 8192
        }
        dim {
          size: 64
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
